In [1]:
from math import *
import numpy as np

# Autoevaluación

## Problema 1

Un sistema de comunicaciones recibe mensajes con una tasa de 8 trabajos por segundo. Se sabe que tanto la llegada como el servicio son procesos de Poisson y que el sistema tiene un factor de utilización del 80%

M/M/1 $\in$ M/G/1

In [2]:
lambda_ = 8

In [3]:
p = 0.8

In [4]:
X = p / lambda_

In [5]:
mu = 1 / X

In [6]:
X_square = 2 / mu**2

Fórmula de Pollaxe-Khintchine

¿Cuál es el tiempo medio de espera?

In [7]:
W = (lambda_ * X_square) / (2 * (1 - p))
W

0.4000000000000001

¿Cuál es el tiempo medio de respuesta? Respuesta

In [8]:
R = W + X
R

0.5000000000000001

¿Cuál es el número medio de mensajes en cola?

In [9]:
Q = lambda_ * W
Q

3.2000000000000006

¿Cuál es el número medio de mensajes en el sistema? Respuesta

In [10]:
J = lambda_ * R
J

4.000000000000001

## Problema 2

Un centro de atención al cliente recibe llamadas de dos tipos: contratación de servicios y petición de información. Las llamadas se producen según procesos de Poisson con tasas de 2 y 11 llamadas por hora según sea de contratación o de petición de información, respectivamente. Las llamadas de contratación requieren una media de 11.4 minutos, mientras que las de petición de información se atienden en una media de 1.9 minutos. Actualmente no hay discriminaciónn en el servicio, pero se ha detectado que algunos clientes que llaman para contratar un servicio abandonan la llamada antes de ser atendidos. Por ello, se ha decidido que se va a implantar un sistema que dé prioridad a estas llamadas. Analizar el modelo que quedaría después de implantar el sistema de prioridades no expulsivas.

In [11]:
lambda1 = 2

In [12]:
lambda2 = 11

In [13]:
X1 = 11.4 / 60

In [14]:
X2 = 1.9 / 60

In [15]:
mu1 = 1 / X1

In [16]:
mu2 = 1 / X2

In [17]:
p1 = lambda1 * X1
p1

0.38

In [18]:
p2 = lambda2 * X2
p2

0.3483333333333333

El sistema actual (sin prioridades) se ajusta a un modelo M/M/1

In [19]:
U1 = p1

In [20]:
U2 = U1 + p2

¿Cuál es el tiempo medio de espera de las llamadas de contratación de servicios?

Sistema no expulsivos con distintas clases de prioridad

In [21]:
X_square1 = 2 / mu1**2
X_square1

0.07219999999999999

In [22]:
X_square2 = 2 / mu2**2
X_square2

0.0020055555555555547

In [23]:
S = (lambda1 * X_square1 + lambda2 * X_square2) / 2
S

0.08323055555555553

¿Cuál es el tiempo medio de espera de las llamadas de contratación de servicios? Respuesta

In [24]:
W1 = S / (1 - U1)
W1 * 60

8.054569892473117

¿Cuál es el tiempo medio de espera de las llamadas de solicitud de información? Respuesta

In [25]:
W2 = S / ((1 - U1) * (1 - U2))
W2 * 60

29.64872353057588

¿Cuál es el número medio de llamadas en cola? Respuesta

In [26]:
Q = lambda1 * W1 + lambda2 * W2
Q

5.704084977021348

¿Cuál es el tiempo medio de respuesta (tiempo que transcurre desde que se inicia hasta que finaliza la llamada)? Respuesta

In [27]:
lambda_ = lambda1 + lambda2

In [28]:
R = ((lambda1 * (W1 + X1)) + (lambda2 * (W2 + X2))) / lambda_
R * 60

29.688084509329297

## Problema 3

Una centralita de venta de entradas por teléfono está preparada atender 2 llamadas simultáneamente sin capacidad para mantener llamadas en espera, de forma que si se recibe una llamada y los 2 operadores están ocupados, la llamada se pierde. Las llamadas se producen según un proceso de Poisson con una tasa de 85 llamadas a la hora, con una duración media de 59 segundos (el proceso de servicio también se ajusta a un proceso de Poisson)

In [29]:
c = 2

In [30]:
lambda_ = 85 / 60

In [31]:
X = 59 / 60

In [32]:
p = lambda_ * X

Este sistema se ajusta a un modelo M/M/m con perdida

¿Qué porcentaje de tiempo la centralita llena?

In [33]:
p_c = p**c / factorial(c) * (1/(sum([p**j/factorial(j) for j in range(0, c+1)])))
p_c * 100

28.849205177095538

¿Qué porcentaje de llamadas se pierden?

In [34]:
p_c * 100

28.849205177095538

La empresa se queda sólo con el operador más eficiente, que en promedio atiende las llamadas en sólo 37 segundos, y contrata un sistema de servicio en espera con capacidad para 3 llamadas, de forma que cuando se recibe una llamada, si el operador está ocupado y ya hay 3 llamadas en espera, la centralita emite la señal de línea ocupada, la llamada se pierde y el cliente se va a la competencia

Este sistema se ajusta a un modelo M/M/1 con buffer limitado

¿Qué porcentaje de llamadas se pierden?

In [35]:
X = 37 / 60

In [36]:
p = lambda_ * X
p

0.8736111111111112

In [37]:
m = 3 + 1

In [38]:
p_m = p**m * (1 - p) / (1 - p**(m + 1))
p_m * 100

14.988851075237305

En esta nueva situación, ¿cuál es el la tasa efectiva de llegada?

In [39]:
lambda_ * (1 - p_m)

1.2043246097674716

¿Cuál es el nivel medio de ocupación del buffer?

In [40]:
J = (p / (1 - p)) - (m + 1) * (p**(m+1) / (1 - p**(m+1)))
J

1.731875095426231

In [41]:
J / m

0.43296877385655774

## Problema 4

Una ventanilla de un banco realiza operaciones en un tiempo medio de 2.3 minutos y los clientes llegan con una tasa media de 16 clientes a la hora. Si se supone que las llegadas siguen un proceso de Poisson y el tiempo de servicio es exponencial.

Este sistema se ajusta a un modelo Respuesta M/M/1

In [42]:
X = 2.3

In [43]:
lambda_ = 16 / 60
lambda_

0.26666666666666666

¿Qué porcentaje de tiempo el cajero está ocioso? Respuesta

In [44]:
p = lambda_* X

In [45]:
p0 = (1 - p)
p0 * 100

38.66666666666667

¿Qué porcentaje de clientes deben esperar en cola?

In [46]:
(1 - p0) * 100

61.33333333333333

¿Cuál es el tiempo medio de estancia de los clientes en el banco

In [47]:
J = p / (1 - p)
J

1.5862068965517238

¿Cuál es el tiempo medio de estancia de los clientes en el banco?

In [48]:
R = J / lambda_
R

5.948275862068964

In [49]:
W = R - X
W

3.6482758620689646

## Problema 5

Una estación de ITV ha sufrido una avería y sólo dispone un equipo de inspección con espacio para 6 coches más en espera. El proceso de llegadas se puede considerar como un proceso de Poisson con una tasa media de un coche cada 17.2 minutos. El tiempo de servicio se puede aproximar mediante una variable aleatoria con distribución exponencial de media 15.2 minutos. Si un coche llega a la estación y esta está saturada, se marcha sin esperar a que quede una plaza libre.

Este sistema se ajusta a un modelo M/M/1 con buffer limitado

In [50]:
m = 6 + 1

In [51]:
lambda_ = 1 / 17.2

In [52]:
X = 15.2

¿Cuál es la probabilidad de que un coche llegue y se encuentre todos los puestos ocupados?

In [53]:
p = lambda_ * X

In [54]:
p_m = p**m * (1 - p) / (1 - p**(m + 1))
p_m

0.07793543657502291

¿Cuál es la tasa efectiva de llegada?

In [55]:
tasa_efectiva = lambda_ * (1 - p_m) * 60
tasa_efectiva

3.216504291017362

¿Cuál es el número medio de coches en el sistema?

In [56]:
J = (p / (1 - p)) - (m + 1)*(p**(m+1)/(1-p**(m+1)))
J

2.8615254562386037

La empresa ha calculado el beneficio por vehículo en 22 euros. Tiene la posibilidad de ampliar la capacidad de la zona de espera en un vehículo más, con lo que la proporción de tiempo en que la estación está saturada disminuye y puede atender a más vehículos Suponiendo que está abierta 8 horas al día, durante 22 días al mes y que el proceso de llegadas es el mismo durante todo el horario de apertura, ¿cuánto sería el incremento mensual en el beneficio esperado por poder atender a los nuevos coches?

In [57]:
m = 6 + 2

In [58]:
precio = 22

In [59]:
hours = 8

In [60]:
days = 22

In [61]:
p_m = p**m * (1 - p) / (1 - p**(m + 1))
p_m

0.06443531189842146

In [62]:
(lambda_ * (1 - p_m) * 60 - tasa_efectiva) * hours * days * precio

182.34587005046873

## Problema 6

Un call center ha recogido datos de las llamadas telefónicas recibidas en el último periodo durante la hora punta. El número de llamadas recibidas se puede aproximar mediante una variable aleatoria con distribución Poisson de media 51 llamadas a la hora. El análisis de las conversaciones revela que la duración media de las llamadas es de 2.5 minutos. Actualmente tiene 3 personas atendiendo el teléfono. Si cuando una persona llama, todos los operarios están ocupados, la llamada se pierde.

Este sistema se ajusta a un modelo M/M/m con pérdidas

In [63]:
lambda_ = 51 / 60

In [64]:
X = 2.5

In [65]:
c = 3

In [66]:
p = lambda_ * X

¿Cuál es la probabilidad de que la llamada se pierda? 

In [67]:
p_c = p**c/factorial(c)/(sum([p**j/factorial(j) for j in range(0, c+1)]))
p_c

0.229054967597557

¿Qué porcentaje de tiempo están todos los operarios ocupados?

In [68]:
p_c * 100

22.9054967597557

¿Qué porcentaje de tiempo están todos los operarios libres?

In [69]:
p_empty = 1/sum([p**j/factorial(j) for j in range(0,c+1)])
p_empty * 100

14.322346030117952

La empresa quiere aumentar el nivel de servicio, reduciendo la probabilidad de que una llamada se encuentre a todos los operarios ocupados. ¿Cuál es el número mínimo de operarios que garantiza que esta probabilidad es inferior a 0.10? Respuesta operarios

In [70]:
k = c
p_k = p**k/factorial(k)/sum([p**j/factorial(j) for j in range(0, k+1)])
while p_k > 0.1:
    k += 1
    p_k = p**k/factorial(k)/sum([p**j/factorial(j) for j in range(0, k+1)])
k

5

## Problema 7

En un determinado se ha implantado un nuevo sistema para el control de seguridad de acceso de los viajeros al área de embarque. Se ha dispuesto una puerta que da acceso a dos arcos detectores de metales que deben superar todos los viajeros de la cola. En caso de que el arco detector no señale ninguna incidencia, el viajero pasa directamente a la zona de embarque. En caso de que detecte algo extraño, el viajero debe pasar a un escáner corporal 3D. Este escaner es el mismo para las dos puertas, de forma que hay una única cola con los viajeros precedentes de las dos puertas. En el caso en el que el escaner corporal 3D siga detectando algo extraño, el viajero debe pasar a un tercer control más exhaustivo, para lo que pasa a unas dependencias especiales del aeropuerto.

Una vez en los viajeros traspasan la puerta de acceso, se reparten por igual entre los dos arcos de seguridad. El 83% de los viajeros que acceden a la zona de embarque, pasan sin problemas por primer arco detector, independientemente de la puerta que usen. El 11% de los viajeros que pasan por el escaner corporal 3D necesitan pasar por las dependencias especiales, mientras que el resto (89%) pasan directamente a la sala de embarque.

Por tanto, se puede considerar que el sistema tiene cinco servidores:

S1 : puerta de acceso a la que llegan todos los viajeros con una tasa λ=80 viajeros por minuto. Este servidor atiende a los viajeros con una tasa μ1 =107 viajeros por minuto.

S2 : primer arco que recibe a la mitad de los viajeros de la puerta de acceso. Este arco tiene una tasa de inspección de μ2 =52 viajeros por minuto.

S3 : segundo arco que recibe a la mitad de los viajeros de la puerta de acceso. Este arco tiene una tasa de inspección de μ3 =52 viajeros por minuto.

S4 : escaner corporal 3D, que recibe a los viajeros a los que los arcos anteriores detectan algo extraño. Este escaner trabaja con una tasa de μ4 =18 viajeros por minuto.

S5 : dependencias especiales, que recibe a todos los viajeros a los que el escaner visual 3D detecta algo extraño. Una vez que ha pasado por aquí, un viajero pasa a la zona de embarque. Cada viajero invierte un promedio de x5 =30 segundos en pasar este proceso.

![Diseño de redes](problema7.png)

Denotamos por Ii la tasa de llegada al servidor i.
Nota: a la hora de realizar los cálculos, es necesario tener en cuenta las unidades eque se utilizan para cada parámetro del problema y las unidades en las que se piden los resultados.
Completa adecuadamente las ecuaciones de tráfico:

In [71]:
lambda_ = 80
mu = np.array([107, 52, 52, 18, 60/30])

In [72]:
q12 = 0.5
q13 = 0.5
q24 = 0.17
q34 = 0.17
q45 = 0.11

In [73]:
I1 = lambda_
I2 = q12 * I1
I3 = q13 * I1
I4 = q24 * I2 + q34 * I3
I5 = q45 * I4
I = np.array([I1, I2, I3, I4, I5])
print(I)

[80.    40.    40.    13.6    1.496]


El número medio de viajeros en cada servidor Ji es:

In [74]:
J = I/(mu-I)
J

array([2.96296296, 3.33333333, 3.33333333, 3.09090909, 2.96825397])

Y el número medio de viajeros en todo el sistema J es Respuesta

In [75]:
np.sum(J)

15.688792688792692

## Problema 8

Una empresa recibe documentos de dos tipos, 1 y 2. Los documentos de tipo 1 deben pasar por el OCR número 1, mientras que los de tipo 2 pasan por el OCR 2. Como resultado de la lectura por el correspondiente OCR, cada documento puede: a) ser rechazado (si la lectura presentó ligeros errores) y sale del sistema, b) pasar a grabación manual (si la lectura fue imposible) o c) pasar directamente al proceso de almacenamiento (distinto para cada tipo de documento). Si un documento pasa por grabación manual, después pasa a cualquiera de los dos procesos de almacenamiento anteriores con la misma probabilidad. Se ha detectado que el 10% de los documentos de tipo 1 son rechazados, el 73% salen correctamente y el 17% restante deben pasar a grabación manual. En el OCR2 (documentos de tipo 2), estos porcentajes son 5%, 74% y 21%, respectivamente.

Por tanto, se puede considerar que el sistema tiene cinco servidores:

S1 : primer OCR, OCR1, que recibe documentos de tipo 1 sólo del exterior con una tasa λ1 =1000 documentos por hora. Los documentos rechazados en este punto, salen del sistema. Este sistema procesa documentos con una tasa μ1 =1357 documentos por hora.

S2 : segundo OCR, OCR2, que recibe documentos de tipo 2 sólo del exterior con una tasa λ2 =550. Los documentos rechazados en este punto, salen del sistema. Este sistema procesa documentos con una tasa μ2 =727 documentos por hora.

S3 : grabación manual, que recibe los documentos de tipo 1 y 2 cuya lectura ha resultado defectuosa. Este sistema procesa documentos con una tasa μ3 =375 documentos por hora.

S4 : primer almacenamiento, que recibe los documentos de tipo 1 que han sido leídos correctamente en el OCR1 y la mitad de los documentos que han pasado por la grabación manual. Una vez que ha pasado por aquí, un documento sale del sistema. Este sistema procesa documentos con una tasa μ4 =1192 documentos por hora.

S5 : primer almacenamiento, que recibe los documentos de tipo 2 que han sido leídos correctamente en el OCR1 y la mitad de los documentos que han pasado por la grabación manual. Una vez que ha pasado por aquí, un documento sale del sistema. Este sistema procesa documentos con una tasa μ5 =666 documentos por hora.

![Diseño de redes](problema8.png)

In [76]:
lambda1 = 1000
lambda2 = 550
mu = np.array([1357, 727, 375, 1192, 666])
q13 = 0.17
q23 = 0.21
q14 = 0.73
q25 = 0.74
q34 = 0.5
q35 = 0.5

Denotamos por Ii la tasa de llegada al servidor i.

Nota: a la hora de realizar los cálculos, es necesario tener en cuenta las unidades eque se utilizan para cada parámetro del problema y las unidades en las que se piden los resultados.

Completa adecuadamente las ecuaciones de tráfico:

In [77]:
I1 = lambda1
I2 = lambda2
I3 = q13 * I1 + q23 * I2
I4 = q14 * I1 + q34 * I3
I5 = q25 * I2 + q35 * I3
I = np.array([I1, I2, I3, I4, I5])
print(I)

[1000.    550.    285.5   872.75  549.75]


El tiempo medio de respuesta de cada servidor es:

In [78]:
R = 1/(mu-I)
R * 60

array([0.16806723, 0.33898305, 0.67039106, 0.18794049, 0.51612903])

Y el tiempo medio de respuesta global es

In [79]:
np.sum(I*R) / (lambda1 + lambda2) * 60

0.6410784174947248