In [1]:
from math import *
import numpy as np
from scipy.special import factorial as np_factorial
np.factorial = np_factorial

Por la naturaleza de incertidumbre, no es posible conocer con exactitud cuántos trabajos llegarían al sistema y qué tipo de servicio van a requerir. Para reducir en la medida de lo posible la espera de los potenciales cuando la demanda de un cierto servicio excede la capacidad del sistema sin que suponga un coste excesivo, es decir, equilibrar el coste del servicio con el coste asociado a la perdida de clientes.

![Sistema de colas](sistemas-de-colas.png)

![Notación de Kendall](kendall.jpg)

Proceso de llegadas: Número de llegadas por unidad de tiempo y el tiempo entre las sucesivas llegadas

Proceso de servicio: Tiempo empleado en dar servicio a un trabajo y por el número de servidores de que se dispone.

Diciplina de la cola: Describe el orden que se da servicio a los trabajos, la más habitual es la FIFO

**N** número de llegadas por unidad de tiempo

**T** tiempo entre dos llegadas consecutivas

**X** tiempo de realización de un servicio

**$\lambda_n$** tasa de llegadas cuando el sistema tiene n clientes

**$\mu_n$** tasa de servicio cuando el sistema tiene n clientes

La cantidad o carga de trabajo en unidades de tiempo o **intensidad de tráfico**: $\lambda \overline{X}$. Si llegan 2 trabajos por minuto y cada trabajo requiere un servicio medio de 0.4 minutos, la intensidad de tráfico es de 0.8 minutos.

Si llegan 2 trabajos por minuto y cada trabajo requiere un servicio medio de 0.4 minutos, la intensidad de tráfico es de 0.8 minutos. Si sólo hay un servidor, el sistema está ocupado el $80$% del tiempo.

El **factor de utilización**: $\rho=\frac{\lambda}{c\mu}$, se puede considerarse como la probabilidad de que el sistema esté ocupado.

Cuando la capacidad sea mayor que la intensidad o $\rho < 1$ se dice que el sistema es **estable**, la desigualdad es **estricta**.

In [2]:
def cal_p(_lambda, mu, c=1):
    p = _lambda / mu / c
    print("p is: ", p)
    return p

assert (cal_p(60, 1/0.1, 7) - 0.857) < 0.001

p is:  0.8571428571428571


El **paso**: Número de llegadas atendidas por unidad de tiempo, si el sistema no admite pérdidas, coincide con la tasa de llegadas.

El **paso máximo** es la capacidad máxima $m\mu$.

En una red de ordenadores, los mensajes tienen un tamaño medio de 500 bits y son transmitidos por una línea de comunicación con una tasa media de 20 mensajes/segundo.

Cuál es la velocidad mínima de la línea necesaria para atender todo el tráfico?$20 * 500 = 10000$ bits/segundo

Cuál es la velocidad mínima de la línea necesaria para atender todo el tráfico si el nivel medio de uso la misma no debe superar el $80$%. $\rho = \frac{10000}{\mu}< 0.8 \implies \mu > \frac{1000}{0.8}=12500$

Cuál es el paso máximo en este segundo caso, si la línea funciona a la velocidad mínima? $\frac{12500}{500}=25$ trabajos.

En un sistema de multiproceso, cada trabajo requiere una media de 100 milisegundos de ejecución. La tasa de llegadas es igual a 60 trabajos por segundo.

Calcular el mínimo número de procesadores que se requieren para atender la demanda. $\rho = \frac{\lambda}{c\mu} = \frac{60}{c*10} < 1 \implies c>6 \implies c=7$

Si se instalan precisamente este número mínimo de procesadores, determinar la tasa de uso y el paso máximo. $\rho=\frac{60}{7*10}=0.85$, y paso máximo es $c*\mu=7*10=70$

# Medidas de eficiencia

La medidas de eficiencia tratan de evaluar la calidad del funcionamiento del sistema.

**$\overline{Q}$** Número medio de trabajos en la cola

**$\overline{W}$** Número medio de espera

**$\overline{J}$** Número medio de trabajo en el sistema

**$\overline{R}$** Tiempo medio de respuesta

# Fórmulas de Little

Proporciona una relación $L=\lambda\overline{W}$ entre el número $L$ promedio a largo plazo de los clientes en un sistema estacionario y el tiempo promedio $\overline{W}$ que un cliente pasa al sistema. 

$$
\begin{split}
\overline{J} &= \lambda\overline{R}\\
\overline{Q} &= \lambda\overline{W}\\
\overline{R} &= \overline{X} + \overline{W}\\
\end{split}
$$

Supongamos que una cola G/G/1 tiene unas tasas de llegada y servicio de 3 y 5 trabajos por segundo, respectivamente.

Además, el número medio de trabajos en la cola es $\overline{Q}=6.7$

Determinar el número medio de trabajos en el sistema y el tiempo medio de respuesta. $\overline{W}=\frac{\overline{Q}}{\lambda}=\frac{6.7}{3}=2.23$, $\overline{X}=\frac{1}{5}=0.2$, $\overline{R}=0.2+2.23=2.43$, $\overline{J}=\lambda\overline{R}$

# Fórmula de Pollaczek-Khintchine

$$C(X) = \frac{\sigma_x}{\overline{X}} = \frac{\sqrt{V(X)}}{\overline{X}} = \frac{\sqrt{\overline{X^2}-\overline{X}^2}}{\overline{X}}$$

Si el timepo de servicio **X** tiene una distribución exponencial de parámetro $\mu$

$$
\begin{split}
\overline{X} &= \frac{1}{\mu}\\
V(X) &= \frac{2}{\mu^2}\\
\overline{X^2} &= \frac{2}{\mu^2}\\
\end{split}
$$

In [3]:
def cal_X2_exponential(mu):
    X_2 = 2 / mu**2
    print("X^2 is: ", X_2)
    return X_2

assert (cal_X2_exponential(10) - 0.02) < 0.001

X^2 is:  0.02


Si un sistema con $M/G/1$

$$
\begin{split}
\overline{W} &= \lambda\frac{\overline{X^2}}{2(1-\rho)}\\
\overline{W} &= \rho\frac{\overline{X}(1+C(X)^2)}{2(1-\rho)}
\end{split}
$$

In [4]:
def cal_W_MG1(lambda_, mu, CX=1):
    p = cal_p(lambda_, mu)
    W = p * (1 + CX**2) / (2 * mu * (1 - p))
    print("W is: ", W)
    return W

Una linea de comunicación recibe mensajes con una tasa de dos mensajes por minuto $\lambda = 2$ mensajes / min. Se transmiten en orden de llegada FIFO, con un tiempo medio de trasmisión de 20 segundos por mensaje $\overline{X} = \frac{20}{60} = \frac{1}{3}$ y una desviación típica de 5 segundos $\sigma_x = 5s = \frac{1}{12}min$.

$$C(X) = \frac{\sigma_x}{\overline{X}} = \frac{\frac{1}{12}}{\frac{1}{3}} = \frac{1}{4}$$

¿Cuál es el tiempo medio de respuesta y el número medio de mensajes en cola?

In [5]:
_lambda = 2
X = 1 / 3
mu = 1 / X
CX = 1 / 4
W = cal_W_MG1(_lambda, mu, CX)
R = W + X
print(R)
assert abs(R - 0.6875) < 0.001

p is:  0.6666666666666666
W is:  0.35416666666666663
0.6875


El mínimo de $\overline{R}$ se alcanza cuando el tiempo de servicio es constante (cola $M/D/1$).

$$\overline{R}=\frac{\rho\overline{X}}{2(1-\rho)}+\overline{X}$$

Si observamos el lote como una única llegada el tiempo medio de espera B se puede obtener a partir de las fórmulas de Pollactek-Khinchine

$$B=\lambda'(b\overline{X})^2\frac{(1+\frac{bV}{(b \overline{X})^2})}{2(1-\lambda' b\overline{X})}$$

El tiempo total de respuesta de un trabajo del lote es

$$\overline{R}=B+\overline{X}\frac{b+1}{2}$$

# Sistemas con prioridad no expulsiva

$\overline{X}_i$ tiempo medio de espera de un trabajo de la clase $i$ se calcula como

$$\overline{W}_i = \overline{S} + D_i + B_i$$

$\overline{S}$ tiempo medio que queda para que se termine el trabajo que actualmente está en el servidor

$$
\overline{S}=\frac{1}{2}\sum_{k=1}^p \lambda_k \overline{X^2_k}
$$

In [6]:
def cal_S(lambdas, X_2):
    S = np.sum(lambdas*X_2, axis=0) / 2
    print("S is: ", S)
    return S

assert abs(cal_S(np.array([0.8, 0.2]), np.array([0.5, 2])) - 0.4) < 0.001

S is:  0.4


$B_i$ tiempo medio de proceso de todos los trabajos de las clases 1 hasta i que ya están en la cola

$D_i$ tiempo medio de proceso de todos los trabajos de las clases 1 hasta $i-1$ que pueden llegar, desde que ha llegado el trabajo hasta que empiece su ejecución.

$$
\begin{split}
U_0 &= 0\\
U_i &= \sum_{k=1}^i \rho_k\\
\end{split}
$$

In [7]:
def cal_U(lambdas, mus):
    p = cal_p(lambdas, mus)
    U = np.array([np.sum(p[:i]) for i in range(p.size + 1)])
    print("U is: ", U)
    return U

$$
\overline{W}_i = \frac{\overline{S}}{(1-U_i)(1-U_{i-1})}
$$

In [8]:
def cal_W_priority_nonpreemptive(S, U):
    W = S / ((1 - U[1:]) * (1 - U[:-1]))
    print("W is: ", W)
    return W

def cal_W_priority_nonpreemptive_MM1(lambdas, mus):
    U = cal_U(lambdas, mus)
    X_2 = cal_X2_exponential(mus)
    S = cal_S(lambdas, X_2)
    return cal_W_priority_nonpreemptive(S, U)

def cal_R_priority_nonpreemptive_MM1(lambdas, mus):
    R = cal_W_priority_nonpreemptive_MM1(lambdas, mus) + 1 / mus
    print("R is: ", R)
    return R

$$
\begin{split}
\overline{W} &= \sum_{k=1}^p \frac{\lambda_k}{\lambda} \overline{W}_k\\
\overline{R} &= \sum_{k=1}^p \frac{\lambda_k}{\lambda} (\overline{W}_k + \overline{X}_k)\\
\end{split}
$$

In [9]:
def cal_weight(lambdas):
    lambda_ = np.sum(lambdas)
    weight = lambdas / lambda_
    print("weights are :", weight)
    return weight

def cal_total_W_priority_nonpreemptive_MM1(lambdas, mus):
    weight = cal_weight(lambdas)
    W = cal_W_priority_nonpreemptive_MM1(lambdas, mus)
    return np.sum(weight * W)

assert abs(cal_total_W_priority_nonpreemptive_MM1(np.array([2, 11]),np.array([60/11.4, 60/1.9])) * 13 - 5.704) < 0.001

def cal_total_R_priority_nonpreemptive_MM1(lambdas, mus):
    weight = cal_weight(lambdas)
    R = cal_R_priority_nonpreemptive_MM1(lambdas, mus)
    return np.sum(weight * R)

assert abs(cal_total_R_priority_nonpreemptive_MM1(np.array([0.8, 0.2]), np.array([1/0.5,1])) - 1.466) < 0.001
assert abs(cal_total_R_priority_nonpreemptive_MM1(np.array([2, 11]), np.array([60/11.4,60/1.9])) * 60 - 29.688) < 0.001

weights are : [0.15384615 0.84615385]
p is:  [0.38       0.34833333]
U is:  [0.         0.38       0.72833333]
X^2 is:  [0.0722     0.00200556]
S is:  0.08323055555555557
W is:  [0.13424283 0.49414539]
weights are : [0.8 0.2]
p is:  [0.4 0.2]
U is:  [0.  0.4 0.6]
X^2 is:  [0.5 2. ]
S is:  0.4
W is:  [0.66666667 1.66666667]
R is:  [1.16666667 2.66666667]
weights are : [0.15384615 0.84615385]
p is:  [0.38       0.34833333]
U is:  [0.         0.38       0.72833333]
X^2 is:  [0.0722     0.00200556]
S is:  0.08323055555555557
W is:  [0.13424283 0.49414539]
R is:  [0.32424283 0.52581206]


En un sistema de prioridades en el proceso de instalación. Todos los trabajos de este proceso tienen las mismas características el tiempo de servicio tiene una distribución exponencial, con 10 milisegundos de tiempo medio de proceso $\overline{X} = 10$ y el momento de segundo orden es es 120 milisegundos $\overline{X^2} = 120$. La opción considerada es crear cinco categorías $k = 5$ de igual tamaño. Suponiendo que hay 10 llegadas por segundo $\lambda_i = \frac{10}{5} = 2$ y que estas llegadas siguen un proceso de Poison, determinar el tiempo medio de espera para cada clase y el tiempo global de espera.

In [10]:
lambdas = np.array([10 / 5 / 1000] * 5) # por milisegundo
X = 10
X_2 = 120
S = cal_S(lambdas, X_2)
assert abs(S - 0.6) < 0.00001

U = cal_U(lambdas, 1 / X)

W = cal_W_priority_nonpreemptive(S, U)
assert np.max(W - np.array([0.612, 0.638, 0.665, 0.694, 0.725])) < 0.001

S is:  0.6
p is:  [0.02 0.02 0.02 0.02 0.02]
U is:  [0.   0.02 0.04 0.06 0.08 0.1 ]
W is:  [0.6122449  0.6377551  0.66489362 0.69380204 0.72463768]


Una linea de comunicación debe transmitir dos tipos de mensajes $k=2$ cada una con una longitud diferente.
La llegada de los mensajes se produce según un proceso de Poisson y la transmisión tiene una distribución exponencial, con una duración media de 0.5 $\overline{X}_1=0.5$ y 1 segundo $\overline{X}_2=1$ para cada tipo de mensaje, respectivamente.
La tasa de llegadas de mensajes es de 1 mensaje por segundo y el 80% son mensajes cortos $\lambda_1=0.8$, $\lambda_2=0.2$.
Comparar la evolución del sistema asignado mayor prioridad a los mensajes cortos o viceversa.

In [11]:
X1 = 0.5
X2 = 1
lambda1 = 0.8
lambda2 = 0.2
R = cal_total_R_priority_nonpreemptive_MM1(np.array([0.8, 0.2]), 1 / np.array([0.5, 1]))
assert abs(R - 1.4666) < 0.001
print(R)

weights are : [0.8 0.2]
p is:  [0.4 0.2]
U is:  [0.  0.4 0.6]
X^2 is:  [0.5 2. ]
S is:  0.4
W is:  [0.66666667 1.66666667]
R is:  [1.16666667 2.66666667]
1.4666666666666668


# Sistema con prioridades explusivas

$$
\begin{split}
\overline{R}_i = H_i + P_i + \overline{X}_i\\
\end{split}
$$

$\overline{H}_i$ tiempo medio en el sistema de los trabajos de las clases 1 a i que ya están en el sistema

$$
\overline{H}_i = \frac{1}{2} \frac{\sum_{k=1}^{i}\lambda_k \overline{X^2_k}}{1 - U_i}
$$

$P_i$ tiempo medio de retraso que se produce por la ejecución de todos los trabajos de las clases 1 a $i - 1$ que lleguen después que dicho trabajo y antes de que acabe su ejecución.

$$
P_i = \sum_{k=1}^{i-1}\lambda_k \overline{X}_k \overline{R}_i = \overline{R}_i U_{i-1}
$$

$\overline{X}_i$ tiempo medio de ejecución de dicho trabajo

$$
\overline{R}_i = \frac{\overline{X}_i}{1 - U_{i-1}} + \frac{\frac{1}{2}\sum_{k=1}^i \lambda_k \overline{X^2_k}}{(1 - U_i)(1 - U_{i-1})}
$$

In [12]:
def cal_R_MM1_preemptive(lambdas, mus):
    U = cal_U(lambdas, mus)
    X_2 = cal_X2_exponential(mus)
    left = (1 / mus) / (1 - U[:-1])
    print("left is: ", left)
    numerator = np.cumsum(lambdas*X_2 / 2)
    print("numerator is: ", numerator)
    denominator = (1 - U[1:]) * (1 - U[:-1])
    print("denominator is: ", denominator)
    right = numerator / denominator
    print("right is: ", denominator)
    R = np.array(left + right)
    print("R is: ", R)
    return R

$$
\overline{R} = \sum_{k=1}^{p} \frac{\lambda_k}{\lambda} \overline{R}_k
$$

In [13]:
def cal_R_total_MM1_preemptive(lambdas, mus):
    weight = cal_weight(lambdas)
    R = cal_R_MM1_preemptive(lambdas, mus)
    return np.sum(weight * R)
    
assert abs(cal_R_total_MM1_preemptive(np.array([0.5, 3, 0.2]), 1 / np.array([0.4, 0.1, 1.5])) - 0.86) < 0.1

weights are : [0.13513514 0.81081081 0.05405405]
p is:  [0.2 0.3 0.3]
U is:  [0.  0.2 0.5 0.8]
X^2 is:  [0.32 0.02 4.5 ]
left is:  [0.4   0.125 3.   ]
numerator is:  [0.08 0.11 0.56]
denominator is:  [0.8 0.4 0.1]
right is:  [0.8 0.4 0.1]
R is:  [0.5 0.4 8.6]


Una CPU soporta tres tipos de tareas cuyas características son:

In [14]:
X1 = 0.4
X2 = 0.1
X3 = 1.5
mus = 1 / np.array([X1, X2, X3])

lambda1 = 0.5
lambda2 = 3.0
lambda3 = 0.2
lambdas = np.array([lambda1, lambda2, lambda3])

cal_R_total_MM1_preemptive(lambdas, mus)

weights are : [0.13513514 0.81081081 0.05405405]
p is:  [0.2 0.3 0.3]
U is:  [0.  0.2 0.5 0.8]
X^2 is:  [0.32 0.02 4.5 ]
left is:  [0.4   0.125 3.   ]
numerator is:  [0.08 0.11 0.56]
denominator is:  [0.8 0.4 0.1]
right is:  [0.8 0.4 0.1]
R is:  [0.5 0.4 8.6]


0.8567567567567568

El funcionamiento global mejora sensiblemente si se permite la interrupcion de trabajos.

# Sistemas de eventos puntuales

Los cambios se producen de forma discreta, el número de trabajos en el sitema cambia cuando se produce una llegada o un salida del sistema.

## Distribución de N

Si la media de llegadas por unidad de tiempo es $\lambda$, el número de llegadas en un invervalo de tiempo $t$ es $\sum_{i=1}^{m}{probabilidad\,en\,el\,subintervalo_i}$ donde $mh=t$, y h es suficientemente pequeño, no se produce más de 1 llega. La probabilidad de obtener k llegadas

$$
\begin{split}
P(N=k) &= \binom{m}{k}\Big(\frac{\lambda t}{m}\Big)^k\Big(1 - \frac{\lambda t}{m}\Big)^{m-k}\\
m \to +\infty \implies &= \frac{(\lambda t)^k e^{-\lambda t}}{k!} \quad Poisson(\lambda t)
\end{split}
$$

La media $\overline{N}=\lambda t$ y la varianza $Var(N)=\lambda t$, se conocen como Procesos de Poisson.

## Distribución de T

La probabilidad de que no se produzcan llegadas en el intervalo $(0, t)$ es

$$
\begin{split}
P(T > t=mh) &= q^m = \Big(1 - \frac{\lambda t}{m}\Big)^m\\
m \to +\infty \implies &= e^{-\lambda t}\\
\end{split}
$$

La función de distribución del timepo entre dos eventos consecutivas es

$$F_T(t) = P(T < t) = 1 - e^{-\lambda t} \quad Exp(\lambda)$$

La función de densidad es

$$
f_T(t) = \lambda e^{-\lambda t}
$$

La media es $\overline{T}=\frac{1}{\lambda}$ y la varianza es $Var(T)=\frac{1}{\lambda^2}$

Supongamos que a un ordenador va llegando trabajos siguiendo un proceso de Poisson. Se sabe que en el periodo de longitud $t$, la probabilidad de que no llegue ningún trabajos es 0.7. Determinar la media y la varianza del número de trabajos llegados en un periodo de longitud $2t$.

$$
\begin{split}
P(t > T) &= 1 - F_T(t) = e^{-\lambda t} = 0.7\\
\lambda t &= \ln(0.7)\\
\end{split}
$$

La media y la varianza del número medio de llegadas en el intervalo (0,t) es precisamente 0.36. En el intervalo (0,2t), los valores serán exactamente el doble 0.72.

Supongamos que estamos estudiando los errores durante al ejecución de un programa. Se sabe que la probabilidad de que se produzca un error o más (de software o hardware) en 15 minutos es del 5%.

Cuál es la tasa de error?

$$
P(t < 15) = 0.05 \implies \lambda = -\frac{\ln{(1-0.05)}}{15} = 0.00341955295
$$

Cuál es la probabilidad de que no se proudzca ningún error en tres horas de ejecución?

P(t > 180) = e^{-180 * 0.003419} = 0.54

# Unión de procesos de Poisson

Un sistema al que llegan trabajos de dos fuentes distintas de procesos de Poisson independientes con tass de llegadas $\lambda_1$ y $\lambda_2$. El número medio de llegadas será la suma de las medias de llegadas de cada uno de los procesos originales.

# División de procesos de Poisson

La división de un proceso en n secuencias, para ello, una llegada se asigna al proceso $p_k$, la tasa de llegada resulta $p_k \lambda$

Supongamos que a un ordenador con $n$ procesadores llegan trabajos según un proceso de Poisson de tasa $\lambda$.

Una vez que un trabajo ha llegado, se asigna a un procesador de forma aleatoria y con la misma probabilidad para los procesadores.

Qué distribución tiene de la variable que mide el tiempo entre dos llegadas consecutivas a cada procesador?

$$\lambda_k = \frac{\lambda}{n}$$

La media y la desviación tipica de cada una de estas variables es $\frac{n}{\lambda}$.

Hallar el coeficiente de variación.

El coeficiente de variación es 1.

Supongamos que a un ordenador con $n$ procesadores llegan trabajos según un proceso de Poisson de tasa $\lambda$.

Una vez que un trabajo ha llegado, se asigna cíclica a cada procesador, de manera que si un trabajo se asigna al procesador $k$, el siguiente trabajo se asignará al procesador $k+1$ o al primero si $k¡n$.

Hallar el coeficiente de variación.

$$
\begin{split}
T &= \sum_i^n{T_i}\\
\overline{X} &= \sum_i^n{\overline{X}_i}=\frac{n}{\lambda}\\
Var{(\sum_n{\overline{X}_i})} &= \sum_n{Var(\overline{X}_i)}=\frac{n}{\lambda^2}\\
C(X) &= \frac{\sqrt{\frac{n}{\lambda^2}}}{\frac{n}{\lambda}}=\frac{1}{\sqrt{n}}\\
\end{split}
$$

Supongamos un sistema con un único procesador que admite tanto trabajos locales como trabajos enviados desde otra máquina remota. La máquina remota envía trabajos con un tasa de 1 por hora y que los dos procesos de llegada son de Poisson. La desviación típica de la variable T, tiempo entre dos llegadas consecutivas, es de 15 minutos.

Determinar la tasa de envío de trabajos de la máquina local.

$$
\begin{split}
\lambda &= \lambda_1 + \lambda_2 = \lambda_1 + 1\\
\sigma &= \frac{15}{60} = \frac{1}{\lambda_1 + 1} \implies \lambda_1 = 3\\
\end{split}
$$

# Procesos de Nacimiento y Muerte

![Diagrama de tasa de transición](diagrama-de-tasa-de-transicion.jpg)

El procesos de nacimiento y muerte describe, en términos probabilísticos, como cambia $N(t)$ el número de trabajos en el sistema al aumentar t.

La probabilidad de que en el sistema haya k clientes $p_k$

Número medio de clientes en el sistema $\sum_{k=0}^{\infty} kp_k=J$

Probabilidad de que haya más de r clientes $\sum_{k=r}^{\infty} p_k$

Número medio de clientes en cola (m servidores) $\sum_{k=m+1}^{\infty} p_k(k-m)$

Probabilidad de que el sistema esté ocioso $p_0$

Si en el sistema hay $N(t)=n$ trabajos, el tiempo hasta el próximo nacimiento tiene una distribución exponencial de parámetro $\lambda_n$

Si en el sistema hay $N(t)=n$ trabajos, el tiempo hasta el próxima muerte tiene una distribución exponencial de parámetro $\mu_n$

Para que en el instante $t+h$ haya $k$ trabajos tiene que ocurrir:

Que en el periodo $t$ haya $k-1$ y se produzca un nacimiento y no se produzca una muerte $p_{k-1}(t)(\lambda_{k-1}h)(1-\mu_{k-1}h)$

Que en el periodo $t$ haya $k$ y no se produzca un nacimiento ni no se produzca una muerte $p_{k}(t)(1-\lambda_{k}h)(1-\mu_kh)$

Que en el periodo $t$ haya $k+1$ y no se produzca un nacimiento pero se produzca una muerte $p_{k+1}(t)(1-\lambda_{k+1}h)(\mu_{k+1}h)$

$$
p_k(t+h) = p_{k-1}(t)(\lambda_{k-1}h)(1-\mu_{k-1}h) + p_{k}(t)(1-\lambda_{k}h)(1-\mu_kh) + p_{k+1}(t)(1-\lambda_{k+1}h)(\mu_{k+1}h)
$$

$$
\begin{split}
p_{k-1}\lambda_{k-1} + p_{k+1}\mu_{k+1} &= p_k\lambda_k + p_k\mu_k\\
p_{i-1}\lambda_{i-1} &= p_i\mu_{i}
\end{split}
$$

$$
\begin{split}
r_i &= \frac{\lambda_{i - 1}}{\mu_i}\\
S_k &= r_1 * ... * r_k\\
p_k &= p_0S_k\\
p_0 &= \frac{1}{\sum{S_k}}
\end{split}
$$

# Sistema M/M/1

$$p_k=(1-\rho)\rho^k$$

In [15]:
def cal_pk_MM1(lambdas, mus, k):
    p = cal_p(lambdas, mus)
    pk = (1 - p)*p**k
    print("p_", k, " is: ", pk)
    return pk

assert abs(cal_pk_MM1(250, 9600/1000*60, 2) - 0.1052) < 0.01

p is:  0.4340277777777778
p_ 2  is:  0.10661791054473166


In [16]:
def cal_pk_MM1_cumulative(lambdas, mus, k):
    pks = []
    for i in range(k + 1):
        pks.append(cal_pk_MM1(lambdas, mus, i))
    print("p_", k, " is: ", pks)
    return np.sum(pks)

$$
\overline{J} = \frac{\rho}{1 - \rho}
$$

In [17]:
def cal_J_MM1(lambdas, mus):
    p = cal_p(lambdas, mus)
    J = p / (1 - p)
    print("J is: ", J)
    return J

$$
\overline{R} = \frac{1}{\mu (1 - \rho)} = \frac{1}{\mu - \lambda}
$$

In [18]:
def cal_R_MM1(lambda_, mu):
    p = cal_p(lambda_, mu)
    R = 1 / (mu * (1 - p))
    print("R is: ", R)
    return R

assert abs(cal_R_MM1(8, 10) - 0.5) < 0.001
assert abs(cal_R_MM1(8, 10) - cal_J_MM1(8, 10) / 8) < 0.001

p is:  0.8
R is:  0.5000000000000001
p is:  0.8
R is:  0.5000000000000001
p is:  0.8
J is:  4.000000000000001


Una línea de comunicaciones transmite a $v=9600$ bps. se producen llegadas de mensajes según un proceso de Poisson con tasa $\lambda = 250$ llegadas por minuto. Los mensajes tienen longitud exponencial con media 1000 bits $\overline{X}=\frac{1000}{9600}$.

In [19]:
X = 1000 / 9600 / 60
_lambda = 250
1 - cal_pk_MM1_cumulative(_lambda, 1/X, 2)

p is:  0.4340277777777778
p_ 0  is:  0.5659722222222222
p is:  0.4340277777777778
p_ 1  is:  0.24564766589506173
p is:  0.4340277777777778
p_ 2  is:  0.10661791054473166
p_ 2  is:  [0.5659722222222222, 0.24564766589506173, 0.10661791054473166]


0.0817622013379844

# Sistema M/M/1 con buffer limitado

El número máximo de clientes en el sistema es $m$

$$
p_k = \rho^k \frac{1 - \rho}{1 - \rho^{m + 1}}
$$

In [20]:
def cal_pk_MM1m(lambda_, mu, m, k):
    p = cal_p(lambda_, mu)
    pk = p**k*(1-p)/(1-p**(m+1))
    print("p_", k, " is:", pk)
    return pk

assert abs(cal_pk_MM1m(85/60, 60/37, 4, 4) * 100 - 14.988851) < 0.001

p is:  0.8736111111111111
p_ 4  is: 0.14988851075237297


In [21]:
def cal_MM1m_loss_probability(lambda_, mu, m):
    return cal_pk_MM1m(lambda_, mu, m, m)

$$
\overline{J}(m) = \frac{\rho}{1 - \rho} - (m + 1)\frac{\rho^{m + 1}}{1 - \rho^{m + 1}}
$$

In [22]:
def cal_J_MM1m(lambda_, mu, m):
    p = cal_p(lambda_, mu)
    J = p / (1 - p)-(m + 1)*(p**(m+1))/(1-p**(m+1))
    print("J is: ", J)
    return J

assert abs(cal_J_MM1m(1/17.2, 1/15.2, 7) - 2.8615254562386037) < 0.001

p is:  0.8837209302325582
J is:  2.8615254562386045


Fracción de tiempo que el sistema está saturado: $p_m$

Nivel medio de ocupación del buffer: $\frac{\overline{J}}{m}$

Tasa efectiva de llegadas: $\lambda (1 - p_m)$

In [23]:
def cal_efective_rate(lambda_, pm):
    return lambda_ * (1 - pm)

assert abs(cal_efective_rate(10, 0.0758) - 9.242) < 0.1

# Sistema M/M/c (Fórmula C de Erlang)

$$
p_0 = \frac{1}{\sum_{k=0}^{c-1}\frac{(c\rho)^k}{k!} + \frac{(c\rho)^c}{c!(1 - \rho)}}
$$

In [24]:
def cal_p0_MMC_without_lost(lambdas, mus, c=1):
    c = np.atleast_1d(c)
    p = cal_p(lambdas, mus, c)
    ks = [np.arange(cc) for cc in c]
    cp = c*p
    right = (c*p)**c/(np.factorial(c)*(1-p))
    left = []
    for k, cp in zip(ks, cp):
        numerator = cp**k
        denominator = np.factorial(k)
        left.append(np.sum(numerator/denominator))
    left = np.array(left)
    p0 = 1 / (left + right)
    print("p0 is: ", p0)
    return p0

assert abs(cal_p0_MMC_without_lost(20, 10, 3) - 1/9) < 0.001

p is:  [0.66666667]
p0 is:  [0.11111111]


$$
p_k = 
     \begin{cases}
       \frac{(c\rho)^k p_0}{k!} &\quad \text{si}\, 0 \le k \le c\\
       \frac{c^c\rho^k p_0}{c!} &\quad \text{si}\, c \le k\\
     \end{cases}
$$

In [25]:
def cal_pk_MMC_without_lost(lambdas, mus, c, k):
    p = cal_p(lambdas, mus, c)
    p0 = cal_p0_MMC_without_lost(lambdas, mus, c)
    if k > 0:
        pk = p0 * c**np.minimum(c, [k]) * p**k / np.minimum(c, [k])
    else:
        pk = p0
    print("p_", k, " is: ", pk)
    return pk

assert (cal_pk_MMC_without_lost(20/60, 1/6, 3, 0) - 1/9) < 0.001
assert (cal_pk_MMC_without_lost(20/60, 1/6, 3, 1) - 2/9) < 0.001
assert (cal_pk_MMC_without_lost(20/60, 1/6, 3, 2) - 4/18) < 0.001

p is:  0.6666666666666666
p is:  [0.66666667]
p0 is:  [0.11111111]
p_ 0  is:  [0.11111111]
p is:  0.6666666666666666
p is:  [0.66666667]
p0 is:  [0.11111111]
p_ 1  is:  [0.22222222]
p is:  0.6666666666666666
p is:  [0.66666667]
p0 is:  [0.11111111]
p_ 2  is:  [0.22222222]


Número medio de procesadores ocupados $c\rho$

Probabilidad de que un trabajo tenga que hacer cola (Fórmula C de Erlang) $\sum_{k=c}^{\infty} p_k$

In [26]:
def cal_pk_serie_without_lost(lambda_, mu, c, k):
    p = cal_p(lambda_, mu, c)
    p0 = cal_p0_MMC_without_lost(lambda_, mu, c)
    p_serie = [p0]
    for i in range(1, k+1):
        p_serie.append(p_serie[i-1] * c * p / i)
    print("The p serie is ", p_serie)
    return np.array(p_serie)

In [27]:
def cal_wait_probability_MMC_without_lost(lambda_, mu, c):
    p_serie = cal_pk_serie_without_lost(lambda_, mu, c, c)
    return 1 - np.sum(p_serie[:-1])

assert abs(cal_wait_probability_MMC_without_lost(20, 10, 3) - 4/9) < 0.001
assert abs(cal_wait_probability_MMC_without_lost(16 / 60, 1 / 2.3, 1) * 100 - 61.33) < 0.01

p is:  0.6666666666666666
p is:  [0.66666667]
p0 is:  [0.11111111]
The p serie is  [array([0.11111111]), array([0.22222222]), array([0.22222222]), array([0.14814815])]
p is:  0.6133333333333333
p is:  [0.61333333]
p0 is:  [0.38666667]
The p serie is  [array([0.38666667]), array([0.23715556])]


Número medio de trabajos en cola

$$
\overline{Q} = \frac{(c\rho)^c \lambda \mu p_0}{(c-1)!(c \mu - \lambda)^2}
$$

In [28]:
def cal_Q_MMC(lambda_, mu, c):
    p = cal_p(lambda_, mu, c)
    p0 = cal_p0_MMC_without_lost(lambda_, mu, c)
    numerator = (c*p)**c * lambda_ * mu * p0
    denominator = np.factorial(c-1)*(c*mu-lambda_)**2
    print(numerator, "/", denominator)
    Q = numerator / denominator
    print("Q is: ", Q)
    return Q

def cal_W_MMC(lambda_, mu, c):
    W = cal_Q_MMC(lambda_, mu, c) / lambda_
    print("W is: ", W)
    return W

def cal_R_MMC(lambda_, mu, c):
    return cal_W_MMC(lambda_, mu, c) + 1 / mu

assert abs(cal_R_MMC(16 / 60, 1 / 2.3, 1) - 5.948) < 0.001

p is:  0.6133333333333333
p is:  [0.61333333]
p0 is:  [0.38666667]
[0.0274963] / 0.02826296996429323
Q is:  [0.97287356]
W is:  [3.64827586]


Un central telefónica está atendrida por tres centralista $c=3$ y recibe llamandas con una tasa de 20 llamadas $\lambda=20$ a la hora con una duración media de 6 minutos $\overline{X}=6$. Dispone de un servicio de espera que se puede considerar de capacidad ilimitada. Tanto el proceso de llegadas como de servicio se pueden considerar procesos de Poisson.

In [29]:
c = 3
X = 6
lambda_ = 20 / 60
p = cal_p(lambda_, 1 / X, c)
assert abs(p - 2/3) < 0.001
p0 = cal_p0_MMC_without_lost(lambda_, 1 / X, c)
assert abs(p0 - 1/9) < 0.001
probability = cal_wait_probability_MMC_without_lost(lambda_, 1 / X, c)
assert abs(probability - 4/9) < 0.001
print(probability)

p is:  0.6666666666666666
p is:  [0.66666667]
p0 is:  [0.11111111]
p is:  0.6666666666666666
p is:  [0.66666667]
p0 is:  [0.11111111]
The p serie is  [array([0.11111111]), array([0.22222222]), array([0.22222222]), array([0.14814815])]
0.4444444444444444


# Sistema M/M/c con pérdidas

Si $\rho$ es $\frac{\lambda}{\mu}$

$$p_k = \frac{\rho^k}{k!}\frac{1}{\sum_{j=0}^c\frac{\rho^j}{j!}} \quad 0 \le k \le c$$

$p_c$ es la probabilidad de que el sistema está lleno, Fórmula B de Erlang

In [30]:
def cal_pk_MMC_with_lost(lambdas, mus, c, k):
    p = cal_p(lambda_, mu)
    return p**k / factorial(k) * 1 / np.sum([(p**j/factorial(j)) for j in range(c+1)])

Consideremos la centralíta anterior en la que se estropea el sistema de llamandas en espera y, por tanto, cuando todas las líneas están ocupadas, la llamada entrante es rechazada.

In [31]:
lambda_ = 20
mu = 1 / 6 * 60
c = 3
p3 = cal_pk_MMC_with_lost(lambda_, mu, c, c)
assert abs(p3 - 0.2105) < 0.001
print(p3)

p is:  2.0
0.21052631578947367


# Sistema M/M/c con buffer limitado

$$
\begin{split}
p_0
&= \frac{1}{\sum_{k=0}^{c-1}\frac{(c\rho)^k}{k!} + \sum_{k=c}^{m}\frac{c^c\rho^k}{c!}}\\
&= \frac{1}{\sum_{k=0}^{c-1}\frac{(c\rho)^k}{k!} + \frac{(1-\rho^{m+1-c})\lambda^c}{c! \mu^c (1-\rho)}}\\
\end{split}
$$

In [32]:
def cal_p0_MMcm(lambda_, mu, c, m):
    p = cal_p(lambda_, mu, c)
    p0 = 1 / (np.sum([(c*p)**k/factorial(k) for k in range(c)]) + (1-p**(m+1-c))*lambda_**c/(factorial(c)*mu**c*(1-p)))
    print("p0 is: ", p0)
    return p0

assert abs(cal_p0_MMcm(20, 10, 3, 5) - 0.128) < 0.001

p is:  0.6666666666666666
p0 is:  0.12796208530805686


$$
p_k = 
     \begin{cases}
       \frac{(c\rho)^k p_0}{k!} &\quad \text{si}\, 0 \le k \le c\\
       \frac{c^c\rho^k p_0}{c!} &\quad \text{si}\, c \le k \le m\\
     \end{cases}
$$

In [33]:
def cal_pk_MMcm(lambda_, mu, c, m, k):
    p = cal_p(lambda_, mu, c)
    p0 = cal_p0_MMcm(lambda_, mu, c, m)
    pk = (c*p)**k/factorial(k)*p0 if k < c else c**c*p**k/factorial(c)*p0
    print("p_", k, " is: ", pk)
    return pk

assert abs(cal_pk_MMcm(20, 10, 3, 5, 5) - 0.0758) < 0.01
assert cal_pk_MM1m(12/60, 1/4, 1, 0) - cal_pk_MMcm(12/60, 1/4, 1, 1, 0) < 0.001

p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
p_ 5  is:  0.0758293838862559
p is:  0.8
p_ 0  is: 0.5555555555555556
p is:  0.8
p is:  0.8
p0 is:  0.5555555555555556
p_ 0  is:  0.5555555555555556


In [34]:
def cal_MMcm_loss_probability(lambda_, mu, c, m):
    return cal_pk_MMcm(lambda_, mu, c, m, m)

$$\overline{J} = \sum_{k=0}^{m} k p_k$$

In [35]:
def cal_J_MMcm(lambda_, mu, c, m):
    p = cal_p(lambda_, mu, c)
    p0 = cal_p0_MMcm(lambda_, mu, c, m)
    p_serie = np.array([c*p/max(k,1) if k < c else p for k in range(m+1)])
    p_serie[0] = p0
    p_serie = np.cumprod(p_serie)
    print("The p serie is ", p_serie)
    J = np.sum(p_serie * np.arange(p_serie.size))
    print("J is: ", J)
    return J

assert abs(cal_J_MMcm(20, 10, 3, 5) - 2.1137) < 0.01
assert abs(cal_J_MMcm(20, 10, 1, 5) - cal_J_MM1m(20, 10, 5)) < 0.000001

p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
The p serie is  [0.12796209 0.25592417 0.25592417 0.17061611 0.11374408 0.07582938]
J is:  2.1137440758293837
p is:  2.0
p is:  2.0
p0 is:  0.015873015873015872
The p serie is  [0.01587302 0.03174603 0.06349206 0.12698413 0.25396825 0.50793651]
J is:  4.095238095238095
p is:  2.0
J is:  4.095238095238095


In [36]:
def cal_R_MMcm(lambda_, mu, c, m):
    J = cal_J_MMcm(lambda_, mu, c, m)
    R = J / lambda_
    print("R is: ", R)
    return R

assert abs(cal_R_MMcm(20, 10, 3, 5) - 0.1056) < 0.01

p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
The p serie is  [0.12796209 0.25592417 0.25592417 0.17061611 0.11374408 0.07582938]
J is:  2.1137440758293837
R is:  0.10568720379146919


In [37]:
def cal_W_MMcm(lambda_, mu, c, m):
    R = cal_R_MMcm(lambda_, mu, c, m)
    W = R - 1/mu
    print("W is: ", W)
    return W

assert abs(cal_W_MMcm(20, 10, 3, 5) * 60 - 0.34) < 0.01

p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
The p serie is  [0.12796209 0.25592417 0.25592417 0.17061611 0.11374408 0.07582938]
J is:  2.1137440758293837
R is:  0.10568720379146919
W is:  0.005687203791469184


Que ocurre si en el ejemplo anterior, la centralita tiene una capacidad limitada en su sistema de espera? Supongamos que sólo puede retener 2 llamadas en espera, de forma que si el sistema tiene 5 llamadas $m=5$ y se recibe una nueva llamada, la llamada entrante es rechazada.

In [38]:
lambda_ = 20
mu = 1 / 6 * 60
c = 3
m = 5
p5 = cal_pk_MMcm(lambda_, mu, c, m, m)
assert abs(p5 - 0.0758) < 0.01
J = cal_J_MMcm(lambda_, mu, c, m)
assert abs(J - 2.1137) < 0.01
R = cal_R_MMcm(lambda_, mu, c, m)
assert abs(R - 0.1056) < 0.001

p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
p_ 5  is:  0.0758293838862559
p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
The p serie is  [0.12796209 0.25592417 0.25592417 0.17061611 0.11374408 0.07582938]
J is:  2.1137440758293837
p is:  0.6666666666666666
p is:  0.6666666666666666
p0 is:  0.12796208530805686
The p serie is  [0.12796209 0.25592417 0.25592417 0.17061611 0.11374408 0.07582938]
J is:  2.1137440758293837
R is:  0.10568720379146919


El sistema está vacío el $12.80$% del tiempo y saturado el $7.58$% del tiempo.

La tasa efectiva de efectiva de llegadas es $10*(1-0.0758)=9.242$.

El número medio de trabajos en el sistema es: $\sum_{k}{k*p_k}=2.1137$, por la tanto, $\overline{R}=0.1056$. Entonces, $\overline{W}=\overline{R}-\overline{X}=0.34$ minutos. Por último $\overline{Q}=\lambda \overline{W} = 20 *\frac{0.34}{60} = 0.1133$ trabajos en cola.

# Redes de colas

Si una **cola M/M/m estable** en la que los procesos de llegada y servicio son **procesos de Poison** con tasas $\lambda$ y $\mu$, el prceso de salida es un proceso de Poisson de tasa $\lambda$

Ses $q_{ij}$ la probabilidad de que un trabajo llega al nodo $i$ y después de haber terminado el servicio requerido en este nodo, pasa al nodo $j$, y sale de la red con probabilidad $1-\sum_{j=1}^{n} q_{ij}$

![Teorema de Jackson](teorema-de-jackson.jpg)

$$
\overline{R}_i = \frac{1}{\mu_i - I_i}
$$

In [39]:
def cal_R_queueing_netowork_MM1(I, mus):
    R = 1 / (mus - I)
    print("R is: ", R)
    return R

$$
\overline{R} = \sum_i{\frac{I_i}{\sum_k \lambda_k}\overline{R}_i}
$$

In [40]:
def cal_R_total_queueing_network(I, R, lambdas):
    lambda_ = np.sum(lambdas)
    print("Total lambda is: ", lambda_)
    return np.sum(I / lambda_ * R)

In [41]:
def cal_R_total_queueing_network_MM1(I, mu, lambdas):
    R = cal_R_queueing_netowork_MM1(I, mu)
    print("R is: ", R)
    return cal_R_total_queueing_network(I, R, lambdas)

assert abs(cal_R_total_queueing_network_MM1(np.array([1000, 550, 285.5, 872.75, 549.75]), np.array([1357, 727, 375, 1192, 666]), 1550) * 60 - 0.641) < 0.001

R is:  [0.00280112 0.00564972 0.01117318 0.00313234 0.00860215]
R is:  [0.00280112 0.00564972 0.01117318 0.00313234 0.00860215]
Total lambda is:  1550


La red de la figura describe un intercambiador de mensajes. Los mensajes del nodo 2 salen con un error con probabilidad $p$ y entonces deben ser enviados de nuevo al nodo 1. En otro caso se envían con igual probabilidad a los nodos 3, 4 y 5.

![Red en paralelo](./red-en-paralelo.jpg)

$$
\begin{split}
I_1 &= \lambda + p I_2\\
I_2 &= I_1\\
I_3 &= \frac{(1-p)I_2}{3}\\
I_4 &= \frac{(1-p)I_2}{3}\\
I_5 &= \frac{(1-p)I_2}{3}\\
I_1 = I_2 &= \frac{\lambda}{(1-p)}\\
I_3 = I_4 = I_5 &= \frac{\lambda}{3}\\
\overline{R}_1 &= \frac{1}{\mu_1 - \frac{\lambda}{1-p}}\\
\overline{R}_2 &= \frac{1}{\mu_2 - \frac{\lambda}{1-p}}\\
\overline{R}_3 &= \frac{1}{\mu_3 - \frac{\lambda}{3}}\\
\overline{R}_4 &= \frac{1}{\mu_3 - \frac{\lambda}{3}}\\
\overline{R}_5 &= \frac{1}{\mu_3 - \frac{\lambda}{3}}\\
\end{split}
$$

La probabilidad de que pase, exactamente, $(n+1)$ veces por el nodo 2 es $(1-p)p^n$. Esto corresponde a una geométrica de parámetro $p$. El número medio de pasadas por el nodo 2 es $\frac{1}{1-p}(\overline{R}_1 + \overline{R}_2)$. Como pasa por 3, 4, 5 con probalidad \frac{1}{3}, el retardo medio total es: $\frac{\lambda}{3}(\overline{R}_1 + \overline{R}_2 + \overline{R}_3)$

![Red en serie](./red-en-serie.jpg)

$$
\begin{split}
\overline{R} &= \sum_i{\overline{R}_i}\\
\overline{J} &= \sum_i{\frac{\lambda}{\mu_i - \lambda}}\\
\end{split}
$$

Dos centros remotos envían mensajes de características similares de comunicación para procesarlos y almacenarlos.

Debido a las distintas velocidades de línea, las tasas de servicio son $\mu_1$ y $\mu_2$.

Las entradas son de Poisson con tasas $\lambda_1$ y $\lambda_2$, respectivamente.

Los mensajes cortos se processan después en la CPU con tasas $\mu_3$ y la salida se via con la misma probabilidad alguno de los dos dispositivos de almancenmiento con tasa $\lambda_4$ y $\lambda_5$, respectivamente.

Todos los tiempos de servicio se suponen exponenciales, salvo en los dispositivos de almacenamiento, que es constante.

![Red](red-merge-split.jpg)

$$
\begin{split}
\overline{R}_1 = \frac{1}{\mu_1 - \lambda_1}\\
\overline{R}_2 = \frac{1}{\mu_2 - \lambda_2}\\
\overline{R}_3 = \frac{1}{\mu_3 - (\lambda_1 + \lambda_2)}
\end{split}
$$

Las entradas a los nodos 4 ó 5 son Poisson con tasa $0.5(\lambda_1 + \lambda_2)$ y al ser tiempos de proceso constantes, aplicamos las fórmula de P-K, donde $\rho_i=\frac{\lambda_1+\lambda_2}{2 \mu_i}$ y $C(X_i)=0$.

$$
\begin{split}
\overline{R}_i &= \overline{W}_i + \overline{X}_i = \frac{\rho_i \overline{X}_i (1 + C(X_i)^2)}{2(1-\rho_i)} = \frac{\rho_i}{2 \mu_i(1-\rho_i)} + \frac{1}{\mu_i}\\
\overline{R}_4 &= \frac{1}{\mu_4}\Bigg(\frac{1}{4\frac{\mu_4}{\lambda_1 + \lambda_2}-2}+1\Bigg)\\
\overline{R}_5 &= \frac{1}{\mu_5}\Bigg(\frac{1}{4\frac{\mu_5}{\lambda_1 + \lambda_2}-2}+1\Bigg)\\
\end{split}
$$

El tiempo de respuesta de los trabajos que llegan a los nodos 1 y 2 es:
    
$$
\begin{split}
\overline{R}^\prime &= \overline{R}_1 + \overline{R}_3 + 0.5(\overline{R}_4 + \overline{R}_5)\\
\overline{R}^{\prime\prime} &= \overline{R}_2 + \overline{R}_3 + 0.5(\overline{R}_4 + \overline{R}_5)\\
\overline{R} &= \frac{\lambda_1}{\lambda_1 + \lambda_2} \overline{R}\prime + \frac{\lambda_2}{\lambda_1 + \lambda_2} \overline{R}{\prime\prime}
\end{split}
$$

![Red](red-ejemplo.jpg)

$$
\begin{split}
I_1 &= \lambda + q I_2\\
I_2 &= I_1 + p I_2\\
I_1 &= \frac{\lambda(r+q)}{r}\\
I_2 &= \frac{\lambda}{r}\\
\end{split}
$$

La razón de uso viene dada por los cocientes de las tasas de llegadas, como $1=p+q+r$, se tiene $p=0.25$

$$
\frac{I_1/\mu}{I_2/\mu} = \frac{\frac{\lambda(r+q)}{r}}{\frac{\lambda}{r}} = r + q = \frac{3}{4}\\
$$

La probabilidad de que los nodos 1 y 2 tengan $k_1$ y $k_2$ trabajos, respectivamente, es:

$$
p^1_{k1} = \rho_1^{k1}(1-\rho_1)\\
p^2_{k2} = \rho_2^{k2}(1-\rho_2)\\
$$

La probabilidad de tengan el mismo número de trabajos es

$$
P(k_1 = k_2) = \sum^\infty_{k=0}{\rho_1^{k1}(1-\rho_1)\rho_2^{k2}(1-\rho_2)} = 0.301
$$

![AP6 Madrid](./highway.jpg)

Determinar el tiempo medio que tarda un vehiculo en cada uno de los seis posibles recorridos y el tiempo medio global

In [42]:
mu1 = 1700
mu2 = 300
mu3 = 300
mu4 = 1200
mu5 = 75
mu6 = 1100
lambda1 = 1000
lambda2 = 80
lambda3 = 175
I4 = 0.1 * lambda1
I5 = 0.05 * lambda1 + 0.1 * lambda2
I6 = 0.85 * lambda1 + 0.9 * lambda2 + lambda3
I = np.array([lambda1, lambda2, lambda3, I4, I5, I6])
mus = np.array([mu1, mu2, mu3, mu4, mu5, mu6])
lambdas = np.array([lambda1, lambda2, lambda3])
cal_R_total_queueing_network_MM1(I, mus, lambdas)

R is:  [0.00142857 0.00454545 0.008      0.00090909 0.05882353 0.33333333]
R is:  [0.00142857 0.00454545 0.008      0.00090909 0.05882353 0.33333333]
Total lambda is:  1255


0.2967024288889768

![Airport](./airport.jpg)

In [43]:
lambda1 = 40 / 60
lambda2 = 40 / 60
X1 = 1.2
X2 = 1.3
X3 = 3.3
X4 = 30
I1 = lambda1
I2 = lambda2
I3 = 0.2 * I1 + 0.2 * I2
I4 = 0.1 * I3
I = np.array([I1, I2, I3, I4])
mus = 1 / np.array([X1, X2, X3, X4])
cal_R_total_queueing_network_MM1(I, mus, np.array([lambda1, lambda2]))

R is:  [  6.     9.75  27.5  150.  ]
R is:  [  6.     9.75  27.5  150.  ]
Total lambda is:  1.3333333333333333


16.375

# Autoevaluación

## Problema 1

Un sistema de comunicaciones recibe mensajes con una tasa de 8 trabajos por segundo. Se sabe que tanto la llegada como el servicio son procesos de Poisson y que el sistema tiene un factor de utilización del 80%

### M/M/1 $\in$ M/G/1

In [44]:
lambda_ = 8

In [45]:
p = 0.8

In [46]:
X = p / lambda_

In [47]:
mu = 1 / X

In [48]:
X_square = cal_X2_exponential(mu)

X^2 is:  0.02


Fórmula de Pollaxe-Khintchine

¿Cuál es el tiempo medio de espera?

In [49]:
W = cal_W_MG1(lambda_, mu, CX=1)
W

p is:  0.8
W is:  0.40000000000000013


0.40000000000000013

### ¿Cuál es el tiempo medio de respuesta? Respuesta

In [50]:
R = W + X
R

0.5000000000000001

### ¿Cuál es el número medio de mensajes en cola?

In [51]:
Q = lambda_ * W
Q

3.200000000000001

### ¿Cuál es el número medio de mensajes en el sistema? Respuesta

In [52]:
J = lambda_ * R
J

4.000000000000001

## Problema 2

Un centro de atención al cliente recibe llamadas de dos tipos: contratación de servicios y petición de información. Las llamadas se producen según procesos de Poisson con tasas de 2 y 11 llamadas por hora según sea de contratación o de petición de información, respectivamente. Las llamadas de contratación requieren una media de 11.4 minutos, mientras que las de petición de información se atienden en una media de 1.9 minutos. Actualmente no hay discriminaciónn en el servicio, pero se ha detectado que algunos clientes que llaman para contratar un servicio abandonan la llamada antes de ser atendidos. Por ello, se ha decidido que se va a implantar un sistema que dé prioridad a estas llamadas. Analizar el modelo que quedaría después de implantar el sistema de prioridades no expulsivas.

In [53]:
lambdas = np.array([2, 11])
mus = 1 / (np.array([11.4, 1.9]) / 60)
print(lambdas, mus)

[ 2 11] [ 5.26315789 31.57894737]


### El sistema actual (sin prioridades) se ajusta a un modelo M/M/1

### ¿Cuál es el tiempo medio de espera de las llamadas de contratación de servicios?

Sistema no expulsivos con distintas clases de prioridad

In [54]:
W = cal_W_priority_nonpreemptive_MM1(lambdas, mus)

p is:  [0.38       0.34833333]
U is:  [0.         0.38       0.72833333]
X^2 is:  [0.0722     0.00200556]
S is:  0.08323055555555553
W is:  [0.13424283 0.49414539]


### ¿Cuál es el tiempo medio de espera de las llamadas de contratación de servicios? Respuesta

In [55]:
W[0] * 60

8.054569892473115

¿Cuál es el tiempo medio de espera de las llamadas de solicitud de información? Respuesta

In [56]:
W[1] * 60

29.648723530575875

¿Cuál es el número medio de llamadas en cola? Respuesta

In [57]:
Q = np.sum(lambdas * W)
Q

5.704084977021347

### ¿Cuál es el tiempo medio de respuesta (tiempo que transcurre desde que se inicia hasta que finaliza la llamada)?

In [58]:
cal_total_R_priority_nonpreemptive_MM1(lambdas, mus) * 60

weights are : [0.15384615 0.84615385]
p is:  [0.38       0.34833333]
U is:  [0.         0.38       0.72833333]
X^2 is:  [0.0722     0.00200556]
S is:  0.08323055555555553
W is:  [0.13424283 0.49414539]
R is:  [0.32424283 0.52581206]


29.688084509329297

## Problema 3

Una centralita de venta de entradas por teléfono está preparada atender 2 llamadas simultáneamente sin capacidad para mantener llamadas en espera, de forma que si se recibe una llamada y los 2 operadores están ocupados, la llamada se pierde. Las llamadas se producen según un proceso de Poisson con una tasa de 85 llamadas a la hora, con una duración media de 59 segundos (el proceso de servicio también se ajusta a un proceso de Poisson)

In [59]:
c = 2
lambda_ = 85 / 60
X = 59 / 60
mu = 1 / X

### Este sistema se ajusta a un modelo M/M/c con perdida

### ¿Qué porcentaje de tiempo la centralita llena?

In [60]:
p_c = cal_MMcm_loss_probability(lambda_, mu, c, c)
p_c * 100

p is:  0.6965277777777779
p is:  0.6965277777777779
p0 is:  0.29732195166855024
p_ 2  is:  0.2884920517709555


28.84920517709555

¿Qué porcentaje de llamadas se pierden?

In [61]:
p_c * 100

28.84920517709555

La empresa se queda sólo con el operador más eficiente, que en promedio atiende las llamadas en sólo 37 segundos, y contrata un sistema de servicio en espera con capacidad para 3 llamadas, de forma que cuando se recibe una llamada, si el operador está ocupado y ya hay 3 llamadas en espera, la centralita emite la señal de línea ocupada, la llamada se pierde y el cliente se va a la competencia

### Este sistema se ajusta a un modelo M/M/1 con buffer limitado

### ¿Qué porcentaje de llamadas se pierden?

In [62]:
X = 37 / 60
mu = 1 / X
m = 3 + 1

In [63]:
p_m = cal_pk_MM1m(lambda_, mu, m, m)
p_m * 100

p is:  0.8736111111111112
p_ 4  is: 0.14988851075237306


14.988851075237305

### En esta nueva situación, ¿cuál es el la tasa efectiva de llegada?

In [64]:
cal_efective_rate(lambda_, p_m)

1.2043246097674716

### ¿Cuál es el nivel medio de ocupación del buffer?

In [65]:
cal_J_MM1m(lambda_, mu, m) / m

p is:  0.8736111111111112
J is:  1.731875095426231


0.43296877385655774

## Problema 4

Una ventanilla de un banco realiza operaciones en un tiempo medio de 2.3 minutos y los clientes llegan con una tasa media de 16 clientes a la hora. Si se supone que las llegadas siguen un proceso de Poisson y el tiempo de servicio es exponencial.

### Este sistema se ajusta a un modelo Respuesta M/M/1

In [66]:
X = 2.3
lambda_ = 16 / 60
mu = 1 / X
print(lambda_, X)

0.26666666666666666 2.3


### ¿Qué porcentaje de tiempo el cajero está ocioso? Respuesta

In [67]:
p0 = cal_pk_MM1(lambda_, mu, 0)
p0 * 100

p is:  0.6133333333333333
p_ 0  is:  0.3866666666666667


38.66666666666667

### ¿Qué porcentaje de clientes deben esperar en cola?

In [68]:
(1 - p0) * 100

61.33333333333333

### ¿Cuál es el tiempo medio de estancia de los clientes en el banco

In [69]:
J = cal_J_MM1(lambda_, mu)
J

p is:  0.6133333333333333
J is:  1.5862068965517238


1.5862068965517238

In [70]:
R = J / lambda_
R

5.948275862068964

In [71]:
W = R - X
W

3.6482758620689646

## Problema 5

Una estación de ITV ha sufrido una avería y sólo dispone un equipo de inspección con espacio para 6 coches más en espera. El proceso de llegadas se puede considerar como un proceso de Poisson con una tasa media de un coche cada 17.2 minutos. El tiempo de servicio se puede aproximar mediante una variable aleatoria con distribución exponencial de media 15.2 minutos. Si un coche llega a la estación y esta está saturada, se marcha sin esperar a que quede una plaza libre.

### Este sistema se ajusta a un modelo M/M/1 con buffer limitado

In [72]:
m = 6 + 1
lambda_ = 1 / 17.2
X = 15.2
mu = 1 / X
print(lambda_, mu, m)

0.05813953488372093 0.06578947368421052 7


### ¿Cuál es la probabilidad de que un coche llegue y se encuentre todos los puestos ocupados?

In [73]:
p_m = cal_pk_MM1m(lambda_, mu, m, m)
p_m

p is:  0.8837209302325582
p_ 7  is: 0.07793543657502297


0.07793543657502297

### ¿Cuál es la tasa efectiva de llegada?

In [74]:
tasa_efectiva = lambda_ * (1 - p_m) * 60
tasa_efectiva

3.2165042910173613

### ¿Cuál es el número medio de coches en el sistema?

In [75]:
cal_J_MM1m(lambda_, mu, m)

p is:  0.8837209302325582
J is:  2.8615254562386045


2.8615254562386045

La empresa ha calculado el beneficio por vehículo en 22 euros. Tiene la posibilidad de ampliar la capacidad de la zona de espera en un vehículo más, con lo que la proporción de tiempo en que la estación está saturada disminuye y puede atender a más vehículos Suponiendo que está abierta 8 horas al día, durante 22 días al mes y que el proceso de llegadas es el mismo durante todo el horario de apertura, ¿cuánto sería el incremento mensual en el beneficio esperado por poder atender a los nuevos coches?

In [76]:
m = 6 + 2

In [77]:
precio = 22

In [78]:
hours = 8

In [79]:
days = 22

In [80]:
p_m = cal_pk_MM1m(lambda_, mu, m, m)
p_m

p is:  0.8837209302325582
p_ 8  is: 0.06443531189842151


0.06443531189842151

In [81]:
(lambda_ * (1 - p_m) * 60 - tasa_efectiva) * hours * days * precio

182.34587005046873

## Problema 6

Un call center ha recogido datos de las llamadas telefónicas recibidas en el último periodo durante la hora punta. El número de llamadas recibidas se puede aproximar mediante una variable aleatoria con distribución Poisson de media 51 llamadas a la hora. El análisis de las conversaciones revela que la duración media de las llamadas es de 2.5 minutos. Actualmente tiene 3 personas atendiendo el teléfono. Si cuando una persona llama, todos los operarios están ocupados, la llamada se pierde.

### Este sistema se ajusta a un modelo M/M/m con pérdidas

In [82]:
lambda_ = 51 / 60
X = 2.5
c = 3
mu = 1 / X
print(lambda_, mu, c)

0.85 0.4 3


### ¿Cuál es la probabilidad de que la llamada se pierda? 

In [83]:
p_c = cal_pk_MMcm(lambda_, mu, c, c, c)
p_c

p is:  0.7083333333333334
p is:  0.7083333333333334
p0 is:  0.14322346030117955
p_ 3  is:  0.22905496759755706


0.22905496759755706

### ¿Qué porcentaje de tiempo están todos los operarios ocupados?

In [84]:
p_c * 100

22.905496759755707

### ¿Qué porcentaje de tiempo están todos los operarios libres?

In [85]:
p_empty = cal_p0_MMcm(lambda_, mu, c, c)
p_empty * 100

p is:  0.7083333333333334
p0 is:  0.14322346030117955


14.322346030117956

La empresa quiere aumentar el nivel de servicio, reduciendo la probabilidad de que una llamada se encuentre a todos los operarios ocupados. ¿Cuál es el número mínimo de operarios que garantiza que esta probabilidad es inferior a 0.10? Respuesta operarios

In [86]:
k = c
p_k = p**k/factorial(k)/sum([p**j/factorial(j) for j in range(0, k+1)])
while p_k > 0.1:
    k += 1
    p_k = p**k/factorial(k)/sum([p**j/factorial(j) for j in range(0, k+1)])
k

3

## Problema 7

En un determinado se ha implantado un nuevo sistema para el control de seguridad de acceso de los viajeros al área de embarque. Se ha dispuesto una puerta que da acceso a dos arcos detectores de metales que deben superar todos los viajeros de la cola. En caso de que el arco detector no señale ninguna incidencia, el viajero pasa directamente a la zona de embarque. En caso de que detecte algo extraño, el viajero debe pasar a un escáner corporal 3D. Este escaner es el mismo para las dos puertas, de forma que hay una única cola con los viajeros precedentes de las dos puertas. En el caso en el que el escaner corporal 3D siga detectando algo extraño, el viajero debe pasar a un tercer control más exhaustivo, para lo que pasa a unas dependencias especiales del aeropuerto.

Una vez en los viajeros traspasan la puerta de acceso, se reparten por igual entre los dos arcos de seguridad. El 83% de los viajeros que acceden a la zona de embarque, pasan sin problemas por primer arco detector, independientemente de la puerta que usen. El 11% de los viajeros que pasan por el escaner corporal 3D necesitan pasar por las dependencias especiales, mientras que el resto (89%) pasan directamente a la sala de embarque.

Por tanto, se puede considerar que el sistema tiene cinco servidores:

S1 : puerta de acceso a la que llegan todos los viajeros con una tasa λ=80 viajeros por minuto. Este servidor atiende a los viajeros con una tasa μ1 =107 viajeros por minuto.

S2 : primer arco que recibe a la mitad de los viajeros de la puerta de acceso. Este arco tiene una tasa de inspección de μ2 =52 viajeros por minuto.

S3 : segundo arco que recibe a la mitad de los viajeros de la puerta de acceso. Este arco tiene una tasa de inspección de μ3 =52 viajeros por minuto.

S4 : escaner corporal 3D, que recibe a los viajeros a los que los arcos anteriores detectan algo extraño. Este escaner trabaja con una tasa de μ4 =18 viajeros por minuto.

S5 : dependencias especiales, que recibe a todos los viajeros a los que el escaner visual 3D detecta algo extraño. Una vez que ha pasado por aquí, un viajero pasa a la zona de embarque. Cada viajero invierte un promedio de x5 =30 segundos en pasar este proceso.

![Diseño de redes](problema7.png)

Denotamos por Ii la tasa de llegada al servidor i.
Nota: a la hora de realizar los cálculos, es necesario tener en cuenta las unidades que se utilizan para cada parámetro del problema y las unidades en las que se piden los resultados.
Completa adecuadamente las ecuaciones de tráfico:

In [87]:
lambda_ = 80
mu = np.array([107, 52, 52, 18, 60/30])

In [88]:
q12 = 0.5
q13 = 0.5
q24 = 0.17
q34 = 0.17
q45 = 0.11

In [89]:
I1 = lambda_
I2 = q12 * I1
I3 = q13 * I1
I4 = q24 * I2 + q34 * I3
I5 = q45 * I4
I = np.array([I1, I2, I3, I4, I5])
print(I)

[80.    40.    40.    13.6    1.496]


El número medio de viajeros en cada servidor Ji es:

In [90]:
J = I/(mu-I)
J

array([2.96296296, 3.33333333, 3.33333333, 3.09090909, 2.96825397])

Y el número medio de viajeros en todo el sistema J es Respuesta

In [91]:
np.sum(J)

15.688792688792692

## Problema 8

Una empresa recibe documentos de dos tipos, 1 y 2. Los documentos de tipo 1 deben pasar por el OCR número 1, mientras que los de tipo 2 pasan por el OCR 2. Como resultado de la lectura por el correspondiente OCR, cada documento puede: a) ser rechazado (si la lectura presentó ligeros errores) y sale del sistema, b) pasar a grabación manual (si la lectura fue imposible) o c) pasar directamente al proceso de almacenamiento (distinto para cada tipo de documento). Si un documento pasa por grabación manual, después pasa a cualquiera de los dos procesos de almacenamiento anteriores con la misma probabilidad. Se ha detectado que el 10% de los documentos de tipo 1 son rechazados, el 73% salen correctamente y el 17% restante deben pasar a grabación manual. En el OCR2 (documentos de tipo 2), estos porcentajes son 5%, 74% y 21%, respectivamente.

Por tanto, se puede considerar que el sistema tiene cinco servidores:

S1 : primer OCR, OCR1, que recibe documentos de tipo 1 sólo del exterior con una tasa λ1 =1000 documentos por hora. Los documentos rechazados en este punto, salen del sistema. Este sistema procesa documentos con una tasa μ1 =1357 documentos por hora.

S2 : segundo OCR, OCR2, que recibe documentos de tipo 2 sólo del exterior con una tasa λ2 =550. Los documentos rechazados en este punto, salen del sistema. Este sistema procesa documentos con una tasa μ2 =727 documentos por hora.

S3 : grabación manual, que recibe los documentos de tipo 1 y 2 cuya lectura ha resultado defectuosa. Este sistema procesa documentos con una tasa μ3 =375 documentos por hora.

S4 : primer almacenamiento, que recibe los documentos de tipo 1 que han sido leídos correctamente en el OCR1 y la mitad de los documentos que han pasado por la grabación manual. Una vez que ha pasado por aquí, un documento sale del sistema. Este sistema procesa documentos con una tasa μ4 =1192 documentos por hora.

S5 : primer almacenamiento, que recibe los documentos de tipo 2 que han sido leídos correctamente en el OCR1 y la mitad de los documentos que han pasado por la grabación manual. Una vez que ha pasado por aquí, un documento sale del sistema. Este sistema procesa documentos con una tasa μ5 =666 documentos por hora.

![Diseño de redes](problema8.png)

In [92]:
lambda1 = 1000
lambda2 = 550
mu = np.array([1357, 727, 375, 1192, 666])
q13 = 0.17
q23 = 0.21
q14 = 0.73
q25 = 0.74
q34 = 0.5
q35 = 0.5

Denotamos por Ii la tasa de llegada al servidor i.

Nota: a la hora de realizar los cálculos, es necesario tener en cuenta las unidades que se utilizan para cada parámetro del problema y las unidades en las que se piden los resultados.

### Completa adecuadamente las ecuaciones de tráfico:

In [93]:
I1 = lambda1
I2 = lambda2
I3 = q13 * I1 + q23 * I2
I4 = q14 * I1 + q34 * I3
I5 = q25 * I2 + q35 * I3
I = np.array([I1, I2, I3, I4, I5])
print(I)

[1000.    550.    285.5   872.75  549.75]


### El tiempo medio de respuesta de cada servidor es:

In [94]:
R = cal_R_queueing_netowork_MM1(I, mu)
R * 60

R is:  [0.00280112 0.00564972 0.01117318 0.00313234 0.00860215]


array([0.16806723, 0.33898305, 0.67039106, 0.18794049, 0.51612903])

### Y el tiempo medio de respuesta global es

In [95]:
cal_R_total_queueing_network_MM1(I, mu, np.array([lambda1, lambda2])) * 60

R is:  [0.00280112 0.00564972 0.01117318 0.00313234 0.00860215]
R is:  [0.00280112 0.00564972 0.01117318 0.00313234 0.00860215]
Total lambda is:  1550


0.6410784174947247

# Serie de problemas y ejercicios de Teoría de Colas

## Problema 1

Una empresa dispone de dos impresoras y cada una atiende la demanda de un departamento. Ambas impresoras son iguales y trabajan a un ritmo promedio de 1.1 trabajos por minuto. El departamento A envía un promedio de 45 trabajos por hora y el departamento B un trabajo cada 90 segundos. Las impresoras tienen capacidad suficiente como para mantener en espera todos los trabajos que se reciban. Tanto las llegadas como el servicio se pueden considerar procesos de Poisson.

In [96]:
lambda1 = 45 / 60
lambda2 = 60 / 90
mu = 1.1
print(lambda1, lambda2, mu)

0.75 0.6666666666666666 1.1


### ¿A qué modelo se ajustan los sistemas descritos? **M/M/1**

### ¿Qué proporción de trabajos tienen que esperar para ser atendidos en cada departamento?

#### Departamento A

In [97]:
cal_p(lambda1, mu)

p is:  0.6818181818181818


0.6818181818181818

#### Departamento B

In [98]:
cal_p(lambda2, mu)

p is:  0.606060606060606


0.606060606060606

### ¿Cuál es el tiempo medio de respuesta en cada una de las dos alternativas?

#### Departamento A:

In [99]:
cal_R_MM1(lambda1, mu)

p is:  0.6818181818181818
R is:  2.8571428571428563


2.8571428571428563

#### Departamento B:

In [100]:
cal_R_MM1(lambda2, mu)

p is:  0.606060606060606
R is:  2.307692307692307


2.307692307692307

La empresa modifica el sistema, unificando las dos colas en una única, de forma que cuando una de las dos impresoras se queda libre, pasa a imprimir el primer trabajo de la cola, independientemente del departamento que lo envió.

### ¿A qué modelo se ajustan los sistemas descritos? **M/M/c**

In [101]:
c = 2

In [102]:
lambda_ = lambda1 + lambda2
lambda_

1.4166666666666665

### ¿Cuál es el tiempo medio de respuesta de los trabajos de cada departamento en esta nueva situación?

#### Departamento A:

In [103]:
cal_R_MMC(lambda_, mu, c)

p is:  0.6439393939393938
p is:  [0.64393939]
p0 is:  [0.21658986]
[0.55982007] / 0.6136111111111117
Q is:  [0.91233692]
W is:  [0.64400253]


array([1.55309344])

#### Departamento B:

In [104]:
cal_R_MMC(lambda_, mu, c)

p is:  0.6439393939393938
p is:  [0.64393939]
p0 is:  [0.21658986]
[0.55982007] / 0.6136111111111117
Q is:  [0.91233692]
W is:  [0.64400253]


array([1.55309344])

La empresa sustituye las dos impresoras por una única impresora el doble de rápido y da más prioridad a los trabajos del departamento A. Una vez iniciada la impresión de un trabajo, no se puede interrumpir.

In [105]:
mu *= 2

### ¿Cuál es el tiempo medio de respuesta de los trabajos de cada departamento, A y B

In [106]:
lambdas = np.array([lambda1, lambda2])
mus = np.array([mu, mu])

In [107]:
R = cal_R_priority_nonpreemptive_MM1(lambdas, mus)

p is:  [0.34090909 0.3030303 ]
U is:  [0.         0.34090909 0.64393939]
X^2 is:  [0.41322314 0.41322314]
S is:  0.29269972451790627
W is:  [0.44409613 1.24724872]
R is:  [0.89864159 1.70179417]


#### Departamento A:

In [108]:
R[0]

0.8986415882967606

#### Departamento B:

In [109]:
R[1]

1.701794170612952

## Problema 2

Una oficina bancaria tiene dos cajeros separados y con un funcionamiento independiente. Cada cajero recibe el 50% de los clientes que requieren este servicio en la oficina bancaria. El banco se está planteando sustituir la organización anterior (que llamaremos alternativa 1) por un sistema con una cola única que sirva a los dos cajeros (el primer cliente de la cola sería atendido por el primer cajero que quede libre), que llamaremos alternativa 2. El banco recibe un promedio de 38 clientes por hora que requieren servicios en el cajero por un promedio de 1.5 minutos para realizar sus gestiones. Tanto las llegadas como el servicio se pueden considerar procesos de Poisson y en todos los casos se puede suponer que las colas tienen capacidad ilimitada.

In [110]:
lambda2 = 38 / 60
mu = 1 / 1.5
print(lambda2, mu)

0.6333333333333333 0.6666666666666666


In [111]:
lambda1 = lambda2 / 2
c = 2

### ¿Qué modelos se ajustan a cada una de las dos alternativas?

Alternativa 1: **M/M/1**

Alternativa 2: **M/M/c**

### ¿Cuál es la tasa de uso del sistema en cada una de las dos alternativas?

#### Alternativa 1:

In [112]:
cal_p(lambda1, mu)

p is:  0.475


0.475

#### Alternativa 2:

In [113]:
cal_p(lambda2, mu, c)

p is:  0.475


0.475

### ¿Cuál es el tiempo medio de respuesta en cada una de las dos alternativas?

#### Alternativa 1:

In [114]:
cal_R_MM1(lambda1, mu)

p is:  0.475
R is:  2.857142857142857


2.857142857142857

#### Alternativa 2:

In [115]:
cal_R_MMC(lambda2, mu, c)

p is:  0.475
p is:  [0.475]
p0 is:  [0.3559322]
[0.13562994] / 0.48999999999999994
Q is:  [0.2767958]
W is:  [0.437046]


array([1.937046])

### ¿Cuál es el tiempo medio de espera en cada una de las dos alternativas?

#### Alternativa 1:

In [116]:
cal_W_MG1(lambda1, mu)

p is:  0.475
W is:  1.3571428571428572


1.3571428571428572

#### Alternativa 2:

In [117]:
cal_W_MMC(lambda2, mu, c)

p is:  0.475
p is:  [0.475]
p0 is:  [0.3559322]
[0.13562994] / 0.48999999999999994
Q is:  [0.2767958]
W is:  [0.437046]


array([0.437046])

### ¿Cuál es la probabilidad de que un cliente tenga que un esperar en cada una de las dos alternativas?

#### Alternativa 1:

In [118]:
cal_wait_probability_MMC_without_lost(lambda1, mu, 1)

p is:  0.475
p is:  [0.475]
p0 is:  [0.525]
The p serie is  [array([0.525]), array([0.249375])]


0.475

#### Alternativa 2:

In [119]:
cal_wait_probability_MMC_without_lost(lambda2, mu, c)

p is:  0.475
p is:  [0.475]
p0 is:  [0.3559322]
The p serie is  [array([0.3559322]), array([0.33813559]), array([0.16061441])]


0.3059322033898304

Los cajeros funcionan 8 horas al día y el banco paga una penalización de 0.1 euros por cada minuto en el que en la cola hay al menos un cliente esperando. 

### ¿Cuál es el coste diario esperado de esta penalización en la alternativa 2?

In [120]:
price = 0.1

In [121]:
(1 - np.sum(cal_pk_serie_without_lost(lambda2, mu, c, c))) * price * 60 * 8

p is:  0.475
p is:  [0.475]
p0 is:  [0.3559322]
The p serie is  [array([0.3559322]), array([0.33813559]), array([0.16061441])]


6.9752542372881265

## Problema 3

Un sistema con dos procesadores recibe trabajos de dos tipos distintos, A y B, con una tasa de 46 y 56 trabajos a la hora, respectivamente. Cada trabajo, independientemente del tipo, tarda en procesarse una media de 50 segundos y es atendido por un único procesador. La cola de espera es suficientemente grande como para mantener en espera todos los trabajos que se reciban. Tanto las llegadas como el servicio se pueden considerar como un proceso de Poisson.

In [122]:
lambdaA = 46 / 60
lambdaB = 56 / 60
mu = 60 / 50
print(lambdaA, lambdaB, mu)

0.7666666666666667 0.9333333333333333 1.2


In [123]:
c = 2
lambda_ = lambdaA + lambdaB

### ¿A qué modelo se ajusta este sistema? M/M/c

### ¿Qué proporción de trabajos tienen que esperar para ser atendidos?

In [124]:
cal_wait_probability_MMC_without_lost(lambda_, mu, c) * 100

p is:  0.7083333333333335
p is:  [0.70833333]
p0 is:  [0.17073171]
The p serie is  [array([0.17073171]), array([0.24186992]), array([0.17132453])]


58.73983739837401

### ¿Cuál es el tiempo medio de espera en el sistema?

In [125]:
cal_W_MMC(lambda_, mu, c)

p is:  0.7083333333333335
p is:  [0.70833333]
p0 is:  [0.17073171]
[0.69900407] / 0.4899999999999996
Q is:  [1.42653891]
W is:  [0.83914053]


array([0.83914053])

Uno de los procesadores se estropea y para paliar la situación, el gestor del sistema decide duplicar la velocidad de proceso de cada trabajo y dar más prioridad a los trabajos de tipo B (aunque en ningún caso se interrumpe el proceso de un trabajo ya en ejecución).

In [126]:
mu *= 2

### ¿Cuál es el tiempo medio de espera de cada uno de los trabajos, A y B?

In [127]:
W_B, W_A = cal_W_priority_nonpreemptive_MM1(np.array([lambdaB, lambdaA]), np.array([mu]*2))

p is:  [0.38888889 0.31944444]
U is:  [0.         0.38888889 0.70833333]
X^2 is:  [0.34722222 0.34722222]
S is:  0.2951388888888889
W is:  [0.48295455 1.65584416]


#### Trabajos de tipo A:

In [128]:
W_A

1.655844155844156

#### Trabajos de tipo B:

In [129]:
W_B

0.4829545454545454

### Promedio de ambos tipos de trabajo:

In [130]:
cal_total_W_priority_nonpreemptive_MM1(np.array([lambdaB, lambdaA]), np.array([mu]*2))

weights are : [0.54901961 0.45098039]
p is:  [0.38888889 0.31944444]
U is:  [0.         0.38888889 0.70833333]
X^2 is:  [0.34722222 0.34722222]
S is:  0.2951388888888889
W is:  [0.48295455 1.65584416]


1.0119047619047619

## Problema 4

Un agente comercial recibe todas sus llamadas en el movil y, para no perder ninguna llamada, ha considerado adecuado desactivar el buzón de voz. De esta forma, cuando recibe una llamada y está ocupado, la llamada se pierde. Recibe un promedio de 12 llamadas a la hora, con una duración media de 4 minutos. Tanto la recepción de llamadas como el tiempo de llamada se pueden considerar procesos de Poisson.

In [131]:
lambda_ = 12 / 60
mu = 1/4
print(lambda_, mu)

0.2 0.25


In [132]:
m = 1

### Este sistema se ajusta a un modelo M/M/1 con perdida

### ¿Que porcentaje de tiempo el agente está ocioso, esperando llamadas?

In [133]:
cal_pk_MM1m(lambda_, mu, m, 0) * 100

p is:  0.8
p_ 0  is: 0.5555555555555556


55.55555555555556

### ¿Que porcentaje de tiempo el agente está ocupado, atendiendo llamadas?

In [134]:
cal_pk_MM1m(lambda_, mu, m, 1) * 100

p is:  0.8
p_ 1  is: 0.44444444444444453


44.44444444444445

### ¿Qué porcentaje de llamadas se pierden? Respuesta

In [135]:
cal_pk_MM1m(lambda_, mu, m, 1) * 100

p is:  0.8
p_ 1  is: 0.44444444444444453


44.44444444444445

Su compañía de teléfono le ofrece un servicio de llamada en espera de capacidad ilimitada. El agente ha calculado que cada llamada atendida le reporta un beneficio de 10 euros. 

In [136]:
profit = 10

### ¿Cuál es el precio máximo por hora que tendría que estar dispuesto a pagar por el alquiler del servicio para que le resulte rentable contratarlo?

In [137]:
lambda_ * cal_pk_MM1m(lambda_, mu, m, 1) * 60 * profit

p is:  0.8
p_ 1  is: 0.44444444444444453


53.33333333333334

El sistema contratado, además, le permite clasificar los clientes y discriminar en función de esta clasificación. El agente ha detectado que el 20% de sus clientes son mejores que el resto y los ha clasificado como super cuquis ya que, a pesar de requerir el mismo tiempo de servicio, le proporcionan un beneficio medio de 30 euros. Por ello, ha decidido darles prioridad y si cuando termina una llamada, hay algún cliente super cuqui en espera, es atendido antes que el resto. 

In [138]:
p_super_cuquis = 0.2

### ¿Cuál es el tiempo medio de respuesta de los clientes super cuquis en cada una de las tres situaciones descritas:

#### Situación inicial:

In [139]:
1 / mu

4.0

#### Situación con servicio de llamada en espera:

In [140]:
cal_R_MM1(lambda_, mu)

p is:  0.8
R is:  20.000000000000004


20.000000000000004

#### Situación con discriminación en las llamadas:

In [141]:
cal_R_priority_nonpreemptive_MM1(np.array([p_super_cuquis, 1-p_super_cuquis])*lambda_, np.array([mu]*2))[0]

p is:  [0.16 0.64]
U is:  [0.   0.16 0.8 ]
X^2 is:  [32. 32.]
S is:  3.2000000000000006
W is:  [ 3.80952381 19.04761905]
R is:  [ 7.80952381 23.04761905]


7.80952380952381

## Problema 5

Una empresa ha recogido datos de las llamadas telefónicas recibidas en los últimos años en horas punta. El tiempo entre llamadas sigue una distribución exponencial con una frecuencia media de 22 llamadas a la hora. El análisis de las conversaciones revela que la duración media de las llamadas es de 4.9 minutos. La empresa tiene 3 operadores atendiendo el teléfono.

In [142]:
lambda_ = 22 / 60
mu = 1 / 4.9
c = 3
print(lambda_, mu, c)

0.36666666666666664 0.2040816326530612 3


### Este sistema se ajusta a un modelo M/M/c

### ¿Cuál es la probabilidad de que ningún operador esté ocupado?

In [143]:
cal_p0_MMC_without_lost(lambda_, mu, c)

p is:  [0.59888889]
p0 is:  [0.14661675]


array([0.14661675])

### ¿Cuál es la probabilidad de que una llamada tenga que esperar por encotnrar a los operadores atendiendo otra llamada? 

In [144]:
cal_wait_probability_MMC_without_lost(lambda_, mu, c)

p is:  0.5988888888888889
p is:  [0.59888889]
p0 is:  [0.14661675]
The p serie is  [array([0.14661675]), array([0.26342142]), array([0.23664024]), array([0.14172121])]


0.35332158458904117

### ¿Cuál es el número medio de operadores ocupados?

In [145]:
def cal_busy_server(lambda_, mu, c):
    p = cal_p(lambda_, mu, c)
    n = c * p
    print("The average of working server is: ", n)
    return n

In [146]:
cal_busy_server(lambda_, mu, c)

p is:  0.5988888888888889
The average of working server is:  1.7966666666666669


1.7966666666666669

### ¿Cuál es el número medio de llamadas en la cola

In [147]:
cal_Q_MMC(lambda_, mu, c)

p is:  0.5988888888888889
p is:  [0.59888889]
p0 is:  [0.14661675]
[0.06362993] / 0.12061733536952189
Q is:  [0.52753555]


array([0.52753555])

### ¿Cuál es el tiempo medio de espera?

In [148]:
cal_Q_MMC(lambda_, mu, c) / lambda_

p is:  0.5988888888888889
p is:  [0.59888889]
p0 is:  [0.14661675]
[0.06362993] / 0.12061733536952189
Q is:  [0.52753555]


array([1.43873332])

## Problema 6

Poisson con unas tasas de llegadas de 13 y 24 trabajos por hora, respectivamente. El tiempo de servicio es exponencial con una tasa de 30 y 72 trabajos por hora para los trabajos A y B, respectivamente. Se considera un modelo de prioridades expulsivas con mayor prioridad a los trabajos A

In [149]:
lambdas = np.array([13, 24])
mus = np.array([30, 72])
print(lambdas, mus)

[13 24] [30 72]


### El modelo sin prioridades sistema se ajusta a un modelo M/M/1

### ¿Cuál es el tiempo medio de respuesta de los trabajos de tipo A?

In [150]:
cal_R_MM1_preemptive(lambdas, mus)[0]

p is:  [0.43333333 0.33333333]
U is:  [0.         0.43333333 0.76666667]
X^2 is:  [0.00222222 0.0003858 ]
left is:  [0.03333333 0.0245098 ]
numerator is:  [0.01444444 0.01907407]
denominator is:  [0.56666667 0.13222222]
right is:  [0.56666667 0.13222222]
R is:  [0.05882353 0.16876751]


0.058823529411764705

### ¿Cuál es el tiempo medio de respuesta de las trabajos de tipo B?

In [151]:
cal_R_MM1_preemptive(lambdas, mus)[1]

p is:  [0.43333333 0.33333333]
U is:  [0.         0.43333333 0.76666667]
X^2 is:  [0.00222222 0.0003858 ]
left is:  [0.03333333 0.0245098 ]
numerator is:  [0.01444444 0.01907407]
denominator is:  [0.56666667 0.13222222]
right is:  [0.56666667 0.13222222]
R is:  [0.05882353 0.16876751]


0.16876750700280108

### ¿Cuál es el tiempo medio de respuesta total?

In [152]:
cal_R_total_MM1_preemptive(lambdas, mus)

weights are : [0.35135135 0.64864865]
p is:  [0.43333333 0.33333333]
U is:  [0.         0.43333333 0.76666667]
X^2 is:  [0.00222222 0.0003858 ]
left is:  [0.03333333 0.0245098 ]
numerator is:  [0.01444444 0.01907407]
denominator is:  [0.56666667 0.13222222]
right is:  [0.56666667 0.13222222]
R is:  [0.05882353 0.16876751]


0.13013854190324775

## Problema 7

Un taller de reparación de vehículos con un funcionamiento continuo (24 horas al día) recibe un promedio de 4 vehículos a la hora. Los vehículos que requieren reparaciones de motor, carrocería o ambas. Los vehículos que requieren simultáneamente a ambas reparaciones son enviados primero a reparación de motor. 

* Los vehículos siguen el siguiente flujo en la empresa: Un clasificador (S1) determina el tipo de avería: motor o carrocería o ambos y envía el vehículo al servicio adecuado. Esta tarea se realiza en un promedio de 6 minutos. Como resultado, se determina que el 10% de los trabajos no son realizables y se descartan; el 35% de los trabajos requieren sólo reparación de carrocería, el 45% sólo de motor y el 10% restante de los dos.

* El servicio de reparación de motor (S2) invierte un promedio de 20 minutos en la reparación. Una vez finalizado el trabajo, los vehículos que requieren reparación de carrocería son enviados al sistema S3, mientras que el resto son enviados a un sistema de preparación del vehículos (S5) para devolvérselo a su propietario (lavado, facturación, etc.).

* El servicio de reparación de carrocería (S3) requiere un promedio de 23 minutos en la reparación. Al final del proceso, los vehículos son enviados al sistema de secado (S4).

* El sistema de secado (S4) requiere un promedio de 11 minutos. Como resultado de este proceso, el 9% de los trabajos son reenviados al sistema de reparación de carrocería, mientras que el resto son enviados al sistema de preparación del vehículo para devolvérselo a su propietario.

* El sistema de preparación del vehículo para devolvérselo a su propietario (S5) requiere un promedio de 7 minutos.

* Se considera que todos los tiempos de proceso de los sistemas se pueden aproximar a una distribución exponencial. El proceso de llegada se puede considerar de Poisson.

Denotamos por $I_i$ la tasa de llegada al servidor i

In [153]:
lambda_ = 4
mus = 1 / np.array([6, 20, 23, 11, 7])
q12 = 0.45
q13 = 0.35
q123 = 0.1
q43 = 0.09
print(lambda_, mus)

4 [0.16666667 0.05       0.04347826 0.09090909 0.14285714]


![Problema7](problema7.jpg)

In [154]:
q23 = q123 / (q12 + q123)
q25 = q12 / (q12 + q123)
q45 = 1 - q43

In [155]:
I1 = lambda_
print("I1=lambda")
I2 = (q12 + q123) * I1
print("I2=", q12+q123, "*I1")
I3 = (q13 * I1 + q23 * I2) / (1 - q43)
print("I3=", q13, "*I1 + ", q23, "*I2 + ", q43, "*I4")
I4 = I3
print("I4=I3")
I5 = q25 * I2 + q45 * I4
print("I5=", q25, "*I2 + ", q45, "*I4")
I = np.array([I1, I2, I3, I4, I5])
print(I)

I1=lambda
I2= 0.55 *I1
I3= 0.35 *I1 +  0.18181818181818182 *I2 +  0.09 *I4
I4=I3
I5= 0.8181818181818181 *I2 +  0.91 *I4
[4.         2.2        1.97802198 1.97802198 3.6       ]


In [156]:
cal_R_total_queueing_network_MM1(I / 60, mus, np.array([lambda_ / 60]))

R is:  [10.         75.         95.13636364 17.25862069 12.06896552]
R is:  [10.         75.         95.13636364 17.25862069 12.06896552]
Total lambda is:  0.06666666666666667


117.69200626959243

## Problema 8

Una empresa de reparación de aparatos electrónicos recibe un promedio de 17 aparatos por hora y tiene el siguiente esquema de funcionamiento:

* Los clientes son atendidos en la recepción por una persona para una inspección básica del aparato y, si procede, tomar nota de los datos y recoger el aparato. Esta operación necesita un tiempo medio de 2.1 minutos. Como resultado, se determina que el 20% tienen daños de software, el 60% de los aparatos tienen daños en el hardware y el 20% restante no son reparables, por lo que son rechazados.

* Los aparatos con daño de software son revisados por un experto en este tipo de daños que procede a un examen más detallado del aparato (para lo que necesita, en promedio, 10 minutos) y, con una descripción detallada de la reparación necesaria, pasa el aparato al taller de reparación de software.

* Los aparatos con daño de hardware son revisados directamente por otro experto en este tipo de daños que procede a un examen más detallado del aparato (para lo que necesita, en promedio, 6 minutos). El 30% de los aparatos son descartados por irreparables, y, previo aviso al cliente, se destruyen; el 40% son sustituidos por un aparato nuevo, se da el aparato por reparado y se envía al departamento de atención al cliente; el 30% restante son enviados al taller de reparación de hardware.

* El taller de software repara un promedio de 10 aparatos por hora y el taller de hardware repara un promedio de 6 aparatos por hora.

* Una vez finalizada la reparación de un aparato, es enviado al departamento de atención al cliente.

* El departamento de atención al cliente procesa el pago de la reparación y el envío del aparato al cliente. Esta operación requiere un tiempo promedio de 4 minutos.

Por tanto, se puede considerar que el sistema tiene seis servidores:

* S1 : servicio de recepción, que recibe los aparatos con una tasa λ=17 aparatos por hora y necesita un promedio de 2.1 minutos para hacer una revisión básica.

* S2 : servicio de revisión de software, que recibe los aparatos que tienen una avería de software desde el servicio de recepción. Necesita un promedio de 10 minutos para revisar detenidamente cada aparato y lo envía directamente al taller de software.

* S3 : servicio de revisión de hardware, que recibe los aparatos que tienen una avería de hadware desde el servicio de recepción. Necesita un promedio de 6 minutos para revisar detenidamente cada aparato y, según la avería, lo envía al taller de hadware, lo sustituye por uno nuevo o lo destruye por irreparable.

* S4 : taller de software, que recibe los aparatos del servicio de revisión de software ( S2 ), después de repararlo (con una tasa μ4 =10), envía el aparato al servicio de atención al cliente.

* S5 : taller de hadware, que recibe los aparatos del servicio de revisión de hadware ( S2 ), después de repararlo (con una tasa μ5 =6), envía el aparato al servicio de atención al cliente.

* S6 : servicio de atención al cliente, que recibe aparatos del servicio de revisión del hadware ( S3 ) y de los dos talleres ( S4 y S5 ). Tramita el pago de la reparación en un promedio de 4 minutos por aparato.

In [157]:
lambda_ = 17
mus = 1 / np.array([2.1, 10, 6, 1/(10/60), 1/(6/60), 4])
q12 = 0.2
q13 = 0.6
q35 = 0.3
q36 = 0.4
print(lambda_, mus)

17 [0.47619048 0.1        0.16666667 0.16666667 0.1        0.25      ]


![Problema8](problema8.jpg)

In [158]:
I1 = lambda_
print("I1=lambda")
I2 = q12 * I1
print("I2=", q12, "*I1")
I3 = q13 * I1
print("I3=", q13, "*I1")
I4 = I2
print("I4=I2")
I5 = q35 * I3
print("I5=", q35, "*I3")
I6 = q36 * I3 + I4 + I5
print("I6=", q36, "*I3 + I4 + I5")
I = np.array([I1, I2, I3, I4, I5, I6])
print(I)

I1=lambda
I2= 0.2 *I1
I3= 0.6 *I1
I4=I2
I5= 0.3 *I3
I6= 0.4 *I3 + I4 + I5
[17.    3.4  10.2   3.4   3.06 10.54]


In [159]:
cal_R_total_queueing_network_MM1(I / 60, mus, np.array([lambda_]) / 60)

R is:  [   5.18518519   23.07692308 -300.            9.09090909   20.40816327
   13.4529148 ]
R is:  [   5.18518519   23.07692308 -300.            9.09090909   20.40816327
   13.4529148 ]
Total lambda is:  0.2833333333333333


-156.36697181860575

# [Prática 2](https://vitaminac.github.io/Caso-De-Estudio-Redes-De-Colas/)

In [160]:
lambda_ = 5000
mu1 = 1 / (4 / 60 / 60)
mu2 = 3 * 60
mu3 = 1 / (5 / 60)
mu_H = 15 * 60
mus = np.array([mu1, mu2, mu3, mu_H])
print(lambda_, mus)

5000 [900. 180.  12. 900.]


In [161]:
I1 = lambda_ / (1 - 0.01)
I2 = (0.15 * 0.99 * I1) / (1 - 0.01)
I3 = (0.2 * 0.99 * I2) / (1 - 0.01)
I_H = 0.85 * 0.99 * I1 + 0.8 * 0.99 * I2 + 0.98 * 0.99 * I3
I_P = 0.02 * 0.99 * I3
I = np.array([I1, I2, I3, I_H, I_P])
print("I in hour is:", I)
assert abs(I_H + I_P - 5000) < 0.00001
T = (1 / I) * 60 * 60
print("T in second is:", T)
print("X in second: ", 1 / mus * 60 *60)

I in hour is: [5.05050505e+03 7.57575758e+02 1.51515152e+02 4.99700000e+03
 3.00000000e+00]
T in second is: [7.12800000e-01 4.75200000e+00 2.37600000e+01 7.20432259e-01
 1.20000000e+03]
X in second:  [  4.  20. 300.   4.]


## La capacidades de cada subsistema para que el nivel de uso sea inferior de 0.8

In [162]:
c = I[:-1] / (0.8 * mus)
print(c)
c = np.ceil(c)
print(c)
c[3] = np.ceil(c[3] / 2) * 2
c

[ 7.01459035  5.26094276 15.78282828  6.94027778]
[ 8.  6. 16.  7.]


array([ 8.,  6., 16.,  8.])

In [163]:
cal_p(I[:-1],mus,c)

p is:  [0.70145903 0.70145903 0.78914141 0.69402778]


array([0.70145903, 0.70145903, 0.78914141, 0.69402778])

### Tiempo medio de inspección total para las maletas.

In [164]:
np.sum(I[:3] / lambda_ * cal_R_MMC(I[:3], mus[:3], c[:3])) * 60 * 60

p is:  [0.70145903 0.70145903 0.78914141]
p is:  [0.70145903 0.70145903 0.78914141]
p0 is:  [3.34060745e-03 1.30843663e-02 2.96894158e-06]
[1.49327972e+10 9.91682504e+06 2.25235093e+15] / [2.32864558e+10 1.24748871e+07 2.14330831e+15]
Q is:  [0.64126535 0.79494307 1.05087585]
W is:  [0.00012697 0.00104932 0.00693578]


17.952316832375416

### Tiempo medio de espera en las distintas colas de los sistemas de inspección y en el hipódromo o zonas de acumulación.

In [165]:
cal_W_MMC(I[:-1], mus, c)[:-1] * 60 * 60

p is:  [0.70145903 0.70145903 0.78914141 0.69402778]
p is:  [0.70145903 0.70145903 0.78914141 0.69402778]
p0 is:  [3.34060745e-03 1.30843663e-02 2.96894158e-06 3.56858570e-03]
[1.49327972e+10 9.91682504e+06 2.25235093e+15 1.44938149e+10] / [2.32864558e+10 1.24748871e+07 2.14330831e+15 2.44601734e+10]
Q is:  [0.64126535 0.79494307 1.05087585 0.59254751]
W is:  [0.00012697 0.00104932 0.00693578 0.00011858]


array([ 0.45709394,  3.77756948, 24.96881008])

Para 4 hipódromo

In [166]:
cal_W_MMC(I_H / 4, mu_H, 2) * 60 * 60

p is:  0.6940277777777778
p is:  [0.69402778]
p0 is:  [0.18061818]
[391261.43032884] / 303325.5625
Q is:  [1.28990589]
W is:  [0.00103254]


array([3.71715927])

### Número de maletas presentes en el sistema

In [167]:
Q = np.concatenate((cal_Q_MMC(I[:-1], mus, c)[:-1], cal_Q_MMC(I[3] / 4, mus[3], 2) * 4), axis=None)
print(Q)
Q_X = (1 / mus) * I[:-1]
print(Q_X)
J =  Q + Q_X
print(J)
np.sum(J)

p is:  [0.70145903 0.70145903 0.78914141 0.69402778]
p is:  [0.70145903 0.70145903 0.78914141 0.69402778]
p0 is:  [3.34060745e-03 1.30843663e-02 2.96894158e-06 3.56858570e-03]
[1.49327972e+10 9.91682504e+06 2.25235093e+15 1.44938149e+10] / [2.32864558e+10 1.24748871e+07 2.14330831e+15 2.44601734e+10]
Q is:  [0.64126535 0.79494307 1.05087585 0.59254751]
p is:  0.6940277777777778
p is:  [0.69402778]
p0 is:  [0.18061818]
[391261.43032884] / 303325.5625
Q is:  [1.28990589]
[0.64126535 0.79494307 1.05087585 5.15962357]
[ 5.61167228  4.20875421 12.62626263  5.55222222]
[ 6.25293763  5.00369728 13.67713847 10.71184579]


35.64561916939008

Para el modelo 2

In [168]:
mus[:3] /= (0.2*2+0.8)
Q = np.concatenate((cal_Q_MMC(I[:-1], mus, c)[:-1], cal_Q_MMC(I[3] / 4, mus[3], 2) * 4), axis=None)
print(Q)
Q_X = (1 / mus) * I[:-1]
print(Q_X)
J =  Q + Q_X
print(J)
np.sum(J)

p is:  [0.84175084 0.84175084 0.9469697  0.69402778]
p is:  [0.84175084 0.84175084 0.9469697  0.69402778]
p0 is:  [8.33893634e-04 4.15926313e-03 1.10441312e-07 3.56858570e-03]
[1.33565748e+10 7.84409026e+06 1.29087637e+15 1.44938149e+10] / [4.54376492e+09 2.43415978e+06 9.41429481e+13 2.44601734e+10]
Q is:  [ 2.93953914  3.22250426 13.71187541  0.59254751]
p is:  0.6940277777777778
p is:  [0.69402778]
p0 is:  [0.18061818]
[391261.43032884] / 303325.5625
Q is:  [1.28990589]
[ 2.93953914  3.22250426 13.71187541  5.15962357]
[ 6.73400673  5.05050505 15.15151515  5.55222222]
[ 9.67354588  8.27300931 28.86339056 10.71184579]


57.52179153613749

In [169]:
np.sum(I[:3] / lambda_ * cal_R_MMC(I[:3], mus[:3], c[:3])) * 60 * 60

p is:  [0.84175084 0.84175084 0.9469697 ]
p is:  [0.84175084 0.84175084 0.9469697 ]
p0 is:  [8.33893634e-04 4.15926313e-03 1.10441312e-07]
[1.33565748e+10 7.84409026e+06 1.29087637e+15] / [4.54376492e+09 2.43415978e+06 9.41429481e+13]
Q is:  [ 2.93953914  3.22250426 13.71187541]
W is:  [0.00058203 0.00425371 0.09049838]


33.703160936433555

# Evaluación

Una gasolinera tiene cinco surtidores situados en paralelo. A la gasolinera llega un promedio de un coche cada minuto que se colocan de forma aleatoria en alguno de los cuatro surtidores, si el surtidor elegido está ocupado, se queda esperando y la gasolinera tiene suficiente espacio para albergar tantos vehículos en espera como sea necesario. El tiempo necesario por cada vehículo para echar combustible y pagar se puede aproxumar por una variable aleatoria con distribución exponencial de media 3.5 minutos(el vehículo se queda ocupando el surtidor hasta que el conductor ha pagado).

Qué modelo se ajusta a este sistema?

5 M/M/1

In [170]:
lambda_i = 1 / 5
X_i = 3.5

Cuál es el tiempo medio que está un vehículo en la gasolinera?

In [171]:
R = cal_R_MM1(lambda_i, 1/X_i)

p is:  0.7000000000000001
R is:  11.66666666666667


Que porcentaje de vehículo se encuentran un surtidor vacío?

In [172]:
cal_pk_MM1(lambda_i, 1/X_i, 0)

p is:  0.7000000000000001
p_ 0  is:  0.29999999999999993


0.29999999999999993

La gerente de la gasolinera considera que el tiempo de esperas es muy alto y ha reorganizado la misma: dos surtidores son de utopago, que incorporan el pago con móvil, el 25% de los clientes optan por este sistema, que suponen que el tiempo de servicio sigue teniendo una distribucion exponencial, pero de media solo 3 minutos.

Qué modelo se ajusta a este sistema?

M/M/2

In [173]:
lambda_ = 0.25
X = 3
c = 2

Cual es el tiempo medio que está un vehículo en la gasolinera si opta por uno de estos surtidores?

In [174]:
cal_R_MMC(lambda_, 1/X, c)

p is:  0.375
p is:  [0.375]
p0 is:  [0.45454545]
[0.02130682] / 0.17361111111111108
Q is:  [0.12272727]
W is:  [0.49090909]


array([3.49090909])

El resto de los vehículos optan por los surtidores tradicionales, pero ahora deben abandonar el surtidor antes de pagar y dirigirse a una caja única para los tres surtidores (con una sola cola con capacidad suficiente para que se pueda suponer ilimitada).El tiempo de servicio de combustible sigue teniendo una distribución exponencial, pero de media solo 2.5 minutos, mientra que el tiempo de pago es de 30 segundos en todos los casos.

Qué modelo se ajusta a este sistema?

![Surtidores](./surtidores.jpg)

In [175]:
lambda1 = 0.75
X1 = 2.5
c = 3

lambda2 = 0.75
X2 = 0.5
CX2 = 0

Cuál es el tiempo medio que está un vehículo en la gasolinera si opta por uno de estos surtidores?

0.625 / (1 - 0.625) / 0.25

In [176]:
R1 = cal_R_MMC(lambda1, 1/X1, c)
print(R1)

p is:  0.625
p is:  [0.625]
p0 is:  [0.1322314]
[0.26149277] / 0.4050000000000003
Q is:  [0.64566116]
W is:  [0.86088154]
[3.36088154]


In [177]:
R2 = cal_W_MG1(lambda2, 1/X2, 0) + X2

p is:  0.375
W is:  0.15


In [178]:
R1 + R2

array([4.01088154])

Qué porcentaje de estos vehículos se encuentran un surtidor vacío?

In [179]:
cal_p0_MMC_without_lost(lambda1, 1/X1, c)

p is:  [0.625]
p0 is:  [0.1322314]


array([0.1322314])

La gerenta de una gasolinera ha decidido reestructurar completamente las instalaciones, para incluir una línea de autolavado y un supermercado autoservicio con una caja. Los cinco surtidores están divididos en dos grupos.

El primer grupo, por el que optan al 25% de los clientes, tiene dos surtidores, una cola única para los dos y es de autopago con tarjeta de crédito (los clientes pagan una vez han colocado el vehículo y antes de reportar). el tiempo medio de servicio es de 3 minuto.

El segundo grupo, con tres surtidores y una cola única para los tres, permite el pago por móvil o el pago en una caja a la que acceden con el vehículo una vez finalizada el repostaje (con una cola común para los vehículos que llegan desde los tres surtidores). El 25% de los clientes de estos servidores se decantan por pagar con el móvil no deben psar por esta caja. En este grupo de servidores el tiempo medio de repostaje es de 2.5 minutos y el pago en caja supone un promedio de 30 segundos(el pago por móvil no supone incremento en el tiempo repostaje).

Una vez realizado y pagado el repostaje, el 10% de los clientes (sea cual sea su método de pago) optan por acudir al centro de autolavado (el programa de lavado dura 5 minutos). Además, la línea de autolavado recibe un promedio de 2 clientes por hora que pasan directamente al lavado de coches, sin repostar previamente. El 80& de los clientes que pasan por el autolavado abandonan las instalaciones con el coche reluciente al finalizar el lavado, peroel resto pasan al autoservicio. Del resto de los vehículos (el 90% de los que repostan en la gasolinera y no han pasado por el autolavado), la mitad van al al autoservicio y la mitad abandonan la instalación. El autoservicio es capaz de atender, en promedio, a 80 clientes a la hora y recibe un promedio de 10 clientes por hora directamente del exterior (que no han pasado por el repostaje ni por la línea de autolavado) y que, como el resto, abandonan las instalaciónes al finalizar su visita al autoservicio.

La gasolinera recibe un vehículo por mínuto y se considera que el tiempo entre dos llegadas puede aproximarse por una distribución exponencial. Todos los sistemas tiene una cola de espera suficientemente grande como para que su capacidad se considere ilimitada. El tiempo de servicio de todos los sistemas (excepto el del autolavado, que es considera fijo), se pueden considerar ajustados a distribuciones exponenciales.

Representar gráficamente el esquema de la red de colas.

![Surtidores Reestructurado](./surtidores-reestructurado.jpg)

In [180]:
lambda_ = 1
lambda_lavado = 2/60
lambda_autoservicio = 10/60
I1 = 0.25 * lambda_
I2 = 0.75 * lambda_
I3 = 0.75 * 0.75 * lambda_
I4 = 0.1 * lambda_ + lambda_lavado
I5 = 0.9 * 0.5 * lambda_ + lambda_autoservicio

Revolver las ecuaciones de tráfico

In [181]:
I = [I1, I2, I3, I4, I5]
print(I)

[0.25, 0.75, 0.5625, 0.13333333333333333, 0.6166666666666667]


Calcular el tiempo medio que cada vehículo está en cada uno de los elementos de la gasolinera.

In [182]:
mu1 = 1/3
mu2 = 1/2.5
mu3 = 1/0.5
mu4 = 1/5
mu5 = 80/60
mus = [mu1, mu2, mu3, mu4, mu5]

In [183]:
R1 = cal_R_MMC(I1, mu1, 2)
R2 = cal_R_MMC(I2, mu2, 3)
R3 = cal_R_MM1(I3, mu3)
R4 = cal_R_MM1(I4, mu4)
R5 = cal_R_MM1(I5, mu5)
print(R1, R2, R3, R4, R5)

p is:  0.375
p is:  [0.375]
p0 is:  [0.45454545]
[0.02130682] / 0.17361111111111108
Q is:  [0.12272727]
W is:  [0.49090909]
p is:  0.625
p is:  [0.625]
p0 is:  [0.1322314]
[0.26149277] / 0.4050000000000003
Q is:  [0.64566116]
W is:  [0.86088154]
p is:  0.28125
R is:  0.6956521739130435
p is:  0.6666666666666666
R is:  14.999999999999996
p is:  0.4625
R is:  1.3953488372093026
[3.49090909] [3.36088154] 0.6956521739130435 14.999999999999996 1.3953488372093026


Calcular el tiempo medio que cada vehículo está en la gasolinera

In [184]:
cal_R_total_queueing_network(I, [R1, R2, R3, R4, R5], [lambda_, lambda_lavado, lambda_autoservicio])

Total lambda is:  1.2000000000000002


array([5.53763158])

In [185]:
(0.25 * 3.49  + 0.75 * 3.36 + 0.5625 * 0.6956 + 0.1333 * 15 + 0.61666 * 1.395) / 1.2

5.536263083333334

In [186]:
1 / (80/60 - 0.6166)

1.3952190493907546

Una centralita de venta de entradas por teléfono está preparada atender una llamada, con la posibilidad de mantener un máximo de tres llamadas en espera. Si cuando se recibe una llamada, ya haya una llamada en marcha y tres esperando, la centralita emite la señal de línea ocupada. la llamada se pierde y el cliente se va a la competencia. Las llamadas se producen según un proceso de Poisson con una tasa de una llamada una cada 2 minutos y el tiempo medio de servicio es de 1 minuto.

A qué tipo de modelo se adapta esta situación?

M/M/1/4

Determinar la proporción de tiempo que la centralita está saturada?

In [187]:
lambda_ = 1 / 2
X = 1
m = 4

In [188]:
cal_MM1m_loss_probability(lambda_, 1/X, m)

p is:  0.5
p_ 4  is: 0.03225806451612903


0.03225806451612903

Se puede reducir el tiempo de servicio, hasta dejarlo en una media de 50 segundos o aumentar la capacidad del sistema para que admita cuatro llamadas en espera. Qué opción proporciona una mejor tasa efectiva de llegadas?

In [189]:
cal_efective_rate(lambda_, cal_MM1m_loss_probability(lambda_, 6/5, m))

p is:  0.4166666666666667
p_ 4  is: 0.017805760519643315


0.49109711974017833

In [190]:
cal_efective_rate(lambda_, cal_MM1m_loss_probability(lambda_, X, 5))

p is:  0.5
p_ 5  is: 0.015873015873015872


0.4920634920634921

es mejor aumentar la capacidad de la cola a 4

Una empresa recibe documentos de dos tipos, 1 y 2. Los documentos de tipo 1 deben pasar por el OCR número 1, mientras que los de tipo 2 pasan por el OCR 2. Como resultado de la lectura por el correspondiente OCR, cada documento puede: 

a) ser rechazado (si la lectura presentó ligeros errores) y sale del sistema, 

b) pasar a grabación manual (si la lectura fue imposible)

c) pasar directamente al proceso de almacenamiento (distinto para cada tipo de documento). 

Si un documento pasa por grabación manual, después pasa a cualquiera de los dos procesos de almacenamiento anteriores con la misma probabilidad. 

![OCR documento](./documento.jpg)

In [191]:
lambda1 = 990
lambda2 = 570
mu = np.array([1300, 800, 300, 1100, 750])
q13 = 0.15
q23 = 0.15
q14 = 0.8
q25 = 0.75
q34 = 0.5
q35 = 0.5

Plantear y resolver las ecuaciones de tráfico.

In [192]:
I1 = lambda1
I2 = lambda2
I3 = q13 * I1 + q23 * I2
I4 = q14 * I1 + q34 * I3
I5 = q25 * I2 + q35 * I3
I = np.array([I1, I2, I3, I4, I5])
print(I)

[990.  570.  234.  909.  544.5]


Calcular el tiempo medio de respuesta de un trabajo, independiente del tipo.

In [193]:
cal_R_total_queueing_network_MM1(I, mu, np.array([lambda1, lambda2])) * 60

R is:  [0.00322581 0.00434783 0.01515152 0.0052356  0.00486618]
R is:  [0.00322581 0.00434783 0.01515152 0.0052356  0.00486618]
Total lambda is:  1560


0.6394638900876081

Calcular el tiempo medio de respuesta de cada tipo de trabajo si se sustituyen los dos OCR por uno nuevo que es capaz de tratar 1700 documentos a la hora (en el que el 90% de los documentos son correctos y el 10% restante la grabación manual) y se sustituyen los dos dispositivos de almacenamiento por uno nuevo capaz de almacenar 2000 documentos por hora. Disminuye el tiempo medio de respuesta global?

In [194]:
I1 = lambda1 + lambda2
I2 = 0.1 * I1
I3 = I1 / 2

In [195]:
mu1 = 1700
mu2 = 300
mu3 = 2000

In [196]:
cal_R_total_queueing_network_MM1(np.array([I1, I2, I3]), np.array([mu1, mu2, mu3]), np.array([lambda1, lambda2])) * 60

R is:  [0.00714286 0.00694444 0.00081967]
R is:  [0.00714286 0.00694444 0.00081967]
Total lambda is:  1560


0.4948282591725215